// Focused, deterministic checks of the actual alchemy component with a small DOM.
// No personal saves, browser instance, service, game action, or disk mutation.
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{spawnSync}=require('node:child_process');
const root=path.resolve(__dirname,'..'),plain=value=>JSON.parse(JSON.stringify(value)),pythonExecutable=process.env.ALCHEMY_TEST_PYTHON||(process.platform==='win32'?'python':'python3');
function python(source,input){const run=spawnSync(pythonExecutable,['-B','-c',source],{cwd:root,input:input===undefined?undefined:JSON.stringify(input),encoding:'utf8',maxBuffer:8*1024*1024});if(run.error)throw run.error;assert.equal(run.status,0,run.stderr);return JSON.parse(run.stdout);}
const metadata=python("import json;from companion.engine import Catalog;from companion.alchemy import recipe_list;from companion.alchemy_flow import family_list,resource_catalog;c=Catalog();print(json.dumps({'recipes':recipe_list(c),'families':family_list(c),'resource_catalog':resource_catalog(c)}))");
const calculate=params=>python("import json,sys;from companion.engine import Catalog;from companion.alchemy import calculate;c=Catalog();print(json.dumps(calculate(c,json.load(sys.stdin))[1]))",params);
const discover=params=>python("import json,sys;from companion.engine import Catalog;from companion.alchemy_flow import discover;c=Catalog();print(json.dumps(discover(c,json.load(sys.stdin))))",params);
const stock=(id,quantity=1,key='s1',state={},origin='manual',reserve=0)=>({key,id,quantity,reserve,origin,state});
const target=(recipe,quantity=1,choices={},key='g1')=>({key,recipe,quantity,choices});
const plan=(targets,resources=[],energy=100,chains={})=>({format:2,recipe_version:'4.0.2',targets,resources,energy,energy_reserve:0,energy_origin:'manual',reference_version:null,chains});
function deferred(){let resolve,reject;return {promise:new Promise((done,fail)=>{resolve=done;reject=fail;}),resolve,reject};}
function harness(initialize=true){
  const elements=new Map();let body;
  class Node{
    constructor(tag){this.tagName=tag.toUpperCase();this.nodeType=tag==='#text'?3:1;this.children=[];this.parentNode=null;this.dataset={};this.listeners={};this.attributes={};this.value='';this.hidden=false;this.disabled=false;this.checked=false;this._text='';}
    set nodeValue(value){this._text=String(value);}get nodeValue(){return this._text;}
    set id(value){this._id=value;elements.set(value,this);}get id(){return this._id||'';}
    set textContent(value){this._text=String(value);for(const row of this.children)row.parentNode=null;this.children=[];}get textContent(){return this._text+this.children.map(row=>row.textContent).join('');}
    set innerHTML(value){this.textContent=value;}get innerHTML(){return this.textContent;}
    get isConnected(){return this===body||!!this.parentNode?.isConnected;}
    get nextSibling(){return this.parentNode?.children[this.parentNode.children.indexOf(this)+1]||null;}
    get firstChild(){return this.children[0]||null;}
    append(...rows){for(const row of rows){row.remove();row.parentNode=this;this.children.push(row);}}
    prepend(...rows){for(const row of rows.reverse()){row.remove();row.parentNode=this;this.children.unshift(row);}}
    insertBefore(row,next){row.remove();const index=next?this.children.indexOf(next):this.children.length;assert(index>=0,'insertBefore requires actual direct child');row.parentNode=this;this.children.splice(index,0,row);}
    remove(){if(this.parentNode){const rows=this.parentNode.children;rows.splice(rows.indexOf(this),1);this.parentNode=null;}}
    replaceChildren(...rows){for(const row of this.children)row.parentNode=null;this.children=[];this._text='';this.append(...rows);}
    setAttribute(key,value){this.attributes[key]=String(value);if(key==='id')this.id=value;if(key.startsWith('data-'))this.dataset[key.slice(5).replace(/-([a-z])/g,(_,v)=>v.toUpperCase())]=String(value);}
    getAttribute(key){return this.attributes[key]??null;}
    addEventListener(name,callback){(this.listeners[name]??=[]).push(callback);}
    async fire(name){for(const callback of this.listeners[name]||[])await callback({target:this,preventDefault(){}});}
    focus(){document.activeElement=this;}
    reportValidity(){return true;}
    closest(tag){let row=this;while(row&&row.tagName!==tag.toUpperCase())row=row.parentNode;return row;}
    querySelectorAll(selector){return walk(this).filter(row=>matches(row,selector));}
  }
  const walk=node=>node.children.flatMap(row=>[row,...walk(row)]);
  const matches=(row,selector)=>selector.startsWith('#')?row.id===selector.slice(1):selector.startsWith('[data-')?row.getAttribute(selector.slice(1,selector.indexOf('=')))===selector.slice(selector.indexOf('="')+2,-2):row.tagName===selector.toUpperCase();
  body=new Node('body');const document={activeElement:null,body,createElement:tag=>new Node(tag),createTextNode:value=>{const row=new Node('#text');row.textContent=value;return row;}};
  const get=selector=>selector.startsWith('#')?(elements.get(selector.slice(1))?.isConnected?elements.get(selector.slice(1)):null):walk(body).find(row=>matches(row,selector))||null;
  const section=new Node('section');body.append(section);const form=new Node('form');form.id='alchemy-form';section.append(form);
  for(const [id,tag,value] of [['alchemy-recipe','select',''],['alchemy-batches','input','1'],['alchemy-formula','p',''],['alchemy-source-link','a',''],['alchemy-materials','div',''],['alchemy-energy','input','0'],['alchemy-energy-reserve','input','0'],['alchemy-energy-origin','p',''],['alchemy-status','p',''],['alchemy-calculate','button',''],['alchemy-use-resources','button',''],['alchemy-undo','button',''],['alchemy-redo','button',''],['alchemy-reload-saved','button','']]){const row=new Node(tag);row.id=id;row.value=value;if(tag==='input'||tag==='select'){const label=new Node('label');if(id==='alchemy-batches')label.append(document.createTextNode('新增目标产出数量（件）'));label.append(row);form.append(label);}else form.append(row);}
  for(const id of ['alchemy-error','alchemy-result','alchemy-save','alchemy-copy','alchemy-copy-text','alchemy-copy-status','alchemy-pending-meta','plan-name','plan-note']){const row=new Node('div');row.id=id;section.append(row);}
  const messages=[],saved=[];const context=vm.createContext({console,URLSearchParams,Map,Set,Promise,Date,JSON,Number,String,Math,document,$:get,$$:selector=>walk(body).filter(row=>matches(row,selector)),
    navigationSerial:0,webEditingFrozen:false,state:{modified:'snapshot-a',active_slot:1},workspaceState:{alchemy:metadata},loadWorkspace:async()=>{},
    inlineError:(node,text)=>{node.textContent=text;node.hidden=!text;},escapeHTML:value=>String(value).replaceAll('<','&lt;'),fmtTime:String,
    cleanStoredOrigin:value=>({mode:value?.mode||'example',snapshot_at:value?.snapshot_at??null,slot:value?.slot??null}),
    toast:message=>messages.push(message),openPlanSave:(...args)=>saved.push(plain(args)),planDraftKey:(payload,existing)=>existing?.id||payload.kind+':draft',planMetaOriginals:new Map(),confirmReloadSavedPlan(){},navigator:{clipboard:{writeText:async()=>{}}},getJSON:async()=>({}),post:async(url,payload)=>payload.action==='alchemy-discover'?discover(payload.params):{result:calculate(payload.params)}});
  const run=source=>vm.runInContext(source,context);run(fs.readFileSync(path.join(root,'web/alchemy.js'),'utf8'));context.metadata=metadata;if(initialize)run('initializeAlchemy(metadata)');
  const field=(container,label,index=0)=>walk(get(container)).filter(row=>['INPUT','SELECT'].includes(row.tagName)&&row.parentNode?.tagName==='LABEL'&&row.parentNode._text===label)[index];
  const button=(container,text)=>walk(get(container)).find(row=>row.tagName==='BUTTON'&&row.textContent===text);
  const apply=params=>{context.params=plain(params);run('applyAlchemyRaw(rawAlchemyParams(params))');};
  return {context,run,get,walk,field,button,apply,messages,saved};
}
async function verifyAlchemyEditHistory(){
  const failures=[];let checks=0;
  const fixture=()=>plan([target('resin',1,{source_key:'original-wand'}),target('potion-healing',2,{},'other-goal')],[stock('items.wands.wandoffireblast',1,'original-wand',{base_level:-1,cursed:false},'known',1)],17,{'items.potions.potionoffrost':{recipe:'seed-potion',choices:{seed_ids:['plants.icecap$seed','plants.icecap$seed','plants.icecap$seed']}}});
  const editor=()=>{const h=harness();h.apply(fixture());h.context.post=async()=>{throw new Error('Editing must not calculate or discover automatically');};return h;};
  const raw=h=>plain(h.run('captureAlchemyRaw()'));
  const undo=h=>h.get('#alchemy-undo').fire('click');
  const redo=h=>{assert(h.get('#alchemy-redo'),'visible redo control');return h.get('#alchemy-redo').fire('click');};
  const check=async(name,run)=>{try{await run();checks++;console.log('history case passed: '+name);}catch(error){failures.push(name+': '+error.message);console.error('history case failed: '+name+'\n'+error.stack);}};
  await check('recipe replacement restores raw invalid amounts and original source_key',async()=>{
    const h=editor(),quantity=h.field('#alchemy-targets','本次希望制作的产出（件）');quantity.value='  unfinished-quantity  ';await quantity.fire('input');
    const reserve=h.field('#alchemy-materials','最低保留（件）');reserve.value='reserve?';await reserve.fire('input');
    const before=raw(h),picker=h.field('#alchemy-targets','目标配方');picker.value='potion-healing';await picker.fire('change');
    assert.equal(raw(h).targets[0].quantity,before.targets[0].quantity);assert.deepEqual(raw(h).targets[1],before.targets[1]);await undo(h);assert.deepEqual(raw(h),before);
    await redo(h);assert.equal(raw(h).targets[0].recipe,'potion-healing');assert.deepEqual(raw(h).targets[0].choices,{});assert.equal(raw(h).resources[0].reserve,'reserve?');
  });
  await check('recipe refresh captures other widgets before rebuilding them',async()=>{
    const h=editor(),before=raw(h);h.field('#alchemy-targets','本次希望制作的产出（件）').value='uncommitted raw quantity';h.field('#alchemy-materials','最低保留（件）').value='uncommitted raw reserve';const picker=h.field('#alchemy-targets','目标配方');picker.value='potion-healing';await picker.fire('change');assert.equal(raw(h).targets[0].quantity,'uncommitted raw quantity');assert.equal(raw(h).resources[0].reserve,'uncommitted raw reserve');await undo(h);before.targets[0].quantity='uncommitted raw quantity';before.resources[0].reserve='uncommitted raw reserve';assert.deepEqual(raw(h),before);
  });
  await check('target removal restores the complete target at its priority',async()=>{
    const h=editor(),before=raw(h);await h.button('#alchemy-targets','移除此目标').fire('click');assert.deepEqual(raw(h).targets,[before.targets[1]]);await undo(h);assert.deepEqual(raw(h),before);await redo(h);assert.deepEqual(raw(h).targets,[before.targets[1]]);
  });
  await check('target reorder and target addition each undo without recalculation',async()=>{
    const h=editor(),before=raw(h);await h.button('#alchemy-targets','下移').fire('click');assert.equal(raw(h).targets[0].key,'other-goal');await undo(h);assert.deepEqual(raw(h),before);
    h.get('#alchemy-recipe').value='potion-healing';h.get('#alchemy-batches').value='invalid new amount';await h.button('#alchemy-target-actions','添加这个产出目标').fire('click');const added=raw(h);assert.equal(added.targets[2].quantity,'invalid new amount');await undo(h);assert.equal(raw(h).targets.length,2);await redo(h);assert.deepEqual(raw(h),added);
  });
  await check('chain recipe replacement restores its concrete material choices',async()=>{
    const h=editor();h.apply({...fixture(),chains:{'items.trinkets.ratskull':{recipe:'trinket-catalyst',choices:{source_key:'original-catalyst',selection:2}}}});const before=raw(h),picker=h.field('#alchemy-chains','明确使用的生产配方');assert(picker.children.some(row=>row.value==='trinket-upgrade'));picker.value='trinket-upgrade';await picker.fire('change');assert.deepEqual(raw(h).chains['items.trinkets.ratskull'].choices,{});await undo(h);assert.deepEqual(raw(h),before);
  });
  await check('chain removal and addition are reversible',async()=>{
    const h=editor(),before=raw(h);await h.button('#alchemy-chains','恢复自动路径 / 删除此选择').fire('click');assert.deepEqual(raw(h).chains,{});await undo(h);assert.deepEqual(raw(h),before);await redo(h);assert.deepEqual(raw(h).chains,{});
    h.get('#alchemy-chain-output').value='items.food.stewedmeat';await h.button('#alchemy-chains','添加前置路径选择').fire('click');assert(raw(h).chains['items.food.stewedmeat']);await undo(h);assert.deepEqual(raw(h).chains,{});
  });
  await check('inventory identity replacement and removal restore state and reserves',async()=>{
    const h=editor(),amount=h.field('#alchemy-materials','原始实例数量（件）');amount.value='bad stock';await amount.fire('input');const before=raw(h),picker=h.field('#alchemy-materials','标准身份');picker.value='items.potions.potionofhealing';await picker.fire('change');await undo(h);assert.deepEqual(raw(h),before);
    await h.button('#alchemy-materials','移除此库存实例').fire('click');assert.equal(raw(h).resources.length,0);await undo(h);assert.deepEqual(raw(h),before);
    h.get('#alchemy-resource-type').value='items.potions.potionofhealing';await h.button('#alchemy-materials','添加一个独立实例').fire('click');assert.equal(raw(h).resources.length,2);await undo(h);assert.deepEqual(raw(h),before);
  });
  await check('unfinished empty selectors remain reversible without relaxing external draft validation',async()=>{
    const h=editor(),before=raw(h),recipe=h.field('#alchemy-targets','目标配方');recipe.value='';await recipe.fire('change');const unfinishedTarget=raw(h);assert.throws(()=>h.run('validateAlchemyRaw(captureAlchemyRaw())'),/目标字段/);await undo(h);assert.deepEqual(raw(h),before);await redo(h);assert.deepEqual(raw(h),unfinishedTarget);await h.button('#alchemy-targets','移除此目标').fire('click');await undo(h);assert.deepEqual(raw(h),unfinishedTarget);
    const identity=h.field('#alchemy-materials','标准身份');identity.value='';await identity.fire('change');const unfinishedResource=raw(h);assert.throws(()=>h.run('validateAlchemyRaw(captureAlchemyRaw())'),/材料字段/);await undo(h);assert.deepEqual(raw(h),unfinishedTarget);await redo(h);assert.deepEqual(raw(h),unfinishedResource);await h.button('#alchemy-materials','移除此库存实例').fire('click');await undo(h);assert.deepEqual(raw(h),unfinishedResource);
  });
  await check('import then edit undo in chronological order and import can redo',async()=>{
    const h=editor(),before=raw(h);h.context.post=async()=>({compatible:true,instances:[stock('items.wands.wandoffireblast',2,'original-wand',{base_level:2,cursed:false},'known')],resources:[],energy:23,reference_version:922,source:{mode:'save',snapshot_at:'imported',slot:2}});
    await h.get('#alchemy-use-resources').fire('click');const imported=raw(h);assert.equal(imported.resources[0].reserve,'');h.run("addAlchemyTarget('potion-healing')");await undo(h);assert.deepEqual(raw(h),imported);await undo(h);assert.deepEqual(raw(h),before);assert.equal(h.run('alchemySource.mode'),'example');await redo(h);assert.deepEqual(raw(h),imported);assert.equal(h.run('alchemySource.snapshot_at'),'imported');
  });
  await check('a new numeric or structural edit clears redo',async()=>{
    const h=editor();await h.button('#alchemy-targets','移除此目标').fire('click');await undo(h);assert(!h.get('#alchemy-redo').disabled);const amount=h.field('#alchemy-targets','本次希望制作的产出（件）');amount.value='new invalid value';await amount.fire('input');assert(h.get('#alchemy-redo').disabled);await redo(h);assert.equal(raw(h).targets[0].quantity,'new invalid value');
    await undo(h);assert(!h.get('#alchemy-redo').disabled);h.run("addAlchemyTarget('potion-healing')");assert(h.get('#alchemy-redo').disabled);
  });
  await check('checkbox changes preserve the original source_key representation on undo',async()=>{
    const h=editor(),before=raw(h),checkbox=h.walk(h.get('#alchemy-targets')).find(row=>row.type==='checkbox');assert(checkbox.checked);checkbox.checked=false;await checkbox.fire('change');const changed=raw(h);assert.deepEqual(changed.targets[0].choices,{source_keys:[]});await undo(h);assert.deepEqual(raw(h),before);await redo(h);assert.deepEqual(raw(h),changed);
  });
  await check('raw energy, reserve and picker edits round trip without numeric coercion',async()=>{
    const h=editor(),before=raw(h);for(const [id,value,event] of [['alchemy-energy','  unknown energy  ','input'],['alchemy-energy-reserve','retain?','input'],['alchemy-batches','pending quantity','input'],['alchemy-recipe','potion-frost','change']]){h.get('#'+id).value=value;await h.get('#'+id).fire(event);}const changed=raw(h);for(let i=0;i<4;i++)await undo(h);assert.deepEqual(raw(h),before);for(let i=0;i<4;i++)await redo(h);assert.deepEqual(raw(h),changed);
  });
  await check('legacy copy conversion can recover its original plan and raw reserves',async()=>{
    const h=editor(),recipe=metadata.recipes.find(row=>row.id==='potion-healing');h.context.saved={id:'legacy-history',kind:'alchemy',name:'Legacy',origin:{mode:'save',snapshot_at:'original',slot:1},record_revision:'d'.repeat(64),note:'Keep metadata',params:{recipe:recipe.id,recipe_version:'4.0.2',batches:2,energy:12,energy_reserve:0,energy_origin:'known',reference_version:922,resources:recipe.inputs.map(row=>({id:row.id,quantity:row.quantity*2,reserve:0,origin:'known'}))}};await h.run('openAlchemyPlan(saved,null,false)');const reserve=h.field('#alchemy-materials','最低保留（件）');reserve.value='invalid reserve';await reserve.fire('input');const before=raw(h),saved=plain(h.run('alchemySavedPlan'));await h.button('#alchemy-target-actions','以产出目标编辑副本').fire('click');const converted=raw(h);assert.equal(converted.format,2);assert.equal(h.run('alchemySavedPlan'),null);await undo(h);assert.deepEqual(raw(h),before);assert.deepEqual(plain(h.run('alchemySavedPlan')),saved);await redo(h);assert.deepEqual(raw(h),converted);assert.equal(h.run('alchemySavedPlan'),null);
  });
  await check('the stated 50-edit history boundary discards only the oldest edits',async()=>{
    const h=editor();for(let i=1;i<=55;i++){const amount=h.field('#alchemy-targets','本次希望制作的产出（件）');amount.value='value-'+i;await amount.fire('input');}for(let i=0;i<50;i++)await undo(h);assert.equal(raw(h).targets[0].quantity,'value-5');assert(h.get('#alchemy-undo').disabled);await undo(h);assert.equal(raw(h).targets[0].quantity,'value-5');for(let i=0;i<50;i++)await redo(h);assert.equal(raw(h).targets[0].quantity,'value-55');assert(h.get('#alchemy-redo').disabled);
  });
  await check('late calculation and discovery cannot replace an undone state',async()=>{
    const h=editor();h.apply(plan([target('potion-healing')],[],11));h.context.post=async(url,payload)=>payload.action==='alchemy-discover'?discover(payload.params):{result:calculate(payload.params)};await h.run('calculateAlchemy()');await h.run('discoverAlchemy()');const before=raw(h),oldResult=plain(h.run('alchemyResult')),oldDiscovery=plain(h.run('alchemyDiscovery'));
    h.run("addAlchemyTarget('potion-frost')");const calculation=deferred(),discovery=deferred();h.context.post=async(url,payload)=>payload.action==='alchemy-discover'?discovery.promise:calculation.promise;const calculating=h.run('calculateAlchemy()'),finding=h.run('discoverAlchemy()');await undo(h);assert.deepEqual(raw(h),before);assert(!h.get('#alchemy-calculate').disabled);assert(!h.get('#alchemy-discover').disabled);
    calculation.resolve({result:{stale:'calculation'}});discovery.resolve({recipes:[],message:'stale discovery'});await calculating;await finding;assert.deepEqual(plain(h.run('alchemyResult')),oldResult);assert.deepEqual(plain(h.run('alchemyDiscovery')),oldDiscovery);assert(!h.run('alchemyDirty'));assert(!h.get('#alchemy-save').disabled);
  });
  await check('redo invalidates pending calculation and discovery failures',async()=>{
    const h=editor();h.run("addAlchemyTarget('potion-healing')");const edited=raw(h);await undo(h);const calculation=deferred(),discovery=deferred();h.context.post=async(url,payload)=>payload.action==='alchemy-discover'?discovery.promise:calculation.promise;const calculating=h.run('calculateAlchemy()'),finding=h.run('discoverAlchemy()');await redo(h);calculation.reject(new Error('obsolete calculation failure'));discovery.reject(new Error('obsolete discovery failure'));await calculating;await finding;assert.deepEqual(raw(h),edited);assert.equal(h.get('#alchemy-error').textContent,'');assert(!h.get('#alchemy-calculate').disabled);assert(!h.get('#alchemy-discover').disabled);assert(h.run('alchemyDirty'));
  });
  await check('an explicit producer path and its calculation can be undone and redone',async()=>{
    const h=editor(),state={cursed:false,is_upgradable:true,level:0,tier:1,default_quantity:3,durability:100};h.apply(plan([target('recipe-telekineticgrab',8)],[stock('items.weapon.missiles.throwingstone',3,'s1',state),stock('items.weapon.missiles.throwingstone',3,'s2',state)],13));let requests=0;h.context.post=async(url,payload)=>{requests++;return {result:calculate(payload.params)};};await h.run('calculateAlchemy()');const before=raw(h),beforeResult=plain(h.run('alchemyResult')),picker=h.walk(h.get('#alchemy-result')).find(row=>row.tagName==='SELECT');assert(picker);picker.value='1';await h.button('#alchemy-result','明确采用此路径并重算').fire('click');const edited=raw(h),editedResult=plain(h.run('alchemyResult'));assert.equal(editedResult.complete,true);assert.equal(requests,2);await undo(h);assert.deepEqual(raw(h),before);assert.deepEqual(plain(h.run('alchemyResult')),beforeResult);await redo(h);assert.deepEqual(raw(h),edited);assert.deepEqual(plain(h.run('alchemyResult')),editedResult);assert.equal(requests,2);
  });
  await check('opening another plan and recovering a draft reset edit history',async()=>{
    const h=editor();h.run("addAlchemyTarget('potion-healing')");h.context.saved={id:'other',kind:'alchemy',name:'Other',origin:{mode:'example'},params:plan([target('potion-healing')],[],31)};await h.run('openAlchemyPlan(saved,null,false)');assert(h.get('#alchemy-undo').disabled);assert(h.get('#alchemy-redo').disabled);h.run("addAlchemyTarget('potion-healing')");const draft=plain(h.run('captureAlchemyDraft()'));h.context.draft=draft;await h.run('restoreAlchemyDraft(draft)');assert(h.get('#alchemy-undo').disabled);assert(h.get('#alchemy-redo').disabled);assert.deepEqual(raw(h),draft.raw);
  });
  await check('undo after a rule update retains the result as stale',async()=>{
    const h=editor();h.apply(plan([target('potion-healing')],[],11));h.context.post=async(url,payload)=>payload.action==='alchemy-discover'?discover(payload.params):{result:calculate(payload.params)};await h.run('calculateAlchemy()');await h.run('discoverAlchemy()');const before=raw(h),result=plain(h.run('alchemyResult'));h.run("addAlchemyTarget('potion-frost')");h.context.changedMetadata=plain(metadata);h.context.changedMetadata.families[0].name+=' changed';h.run('initializeAlchemy(changedMetadata)');await undo(h);assert.deepEqual(raw(h),before);assert.deepEqual(plain(h.run('alchemyResult')),result);assert(h.run('alchemyDirty&&alchemyRuleChanged'));assert(h.get('#alchemy-save').disabled);assert(h.get('#alchemy-discovery-status').textContent.includes('旧库存'));
  });
  assert.equal(failures.length,0,JSON.stringify({history_failures:failures},null,2));return checks;
}
async function verifyAlchemyResinBoundary(){
  let checks=0;
  const fixture=points=>plan([target('resin',5,{source_keys:['wand']})],[stock('items.wands.wandofmagicmissile',1,'wand',{cursed:false,base_level:0,public_level:0,resin_bonus:0,hero_class:'WARRIOR',wand_preservation:points})],5);
  for(const points of [0,1,2]){
    const h=harness();h.apply(fixture(points));await h.run('calculateAlchemy()');
    assert.equal(h.run('alchemyResult.targets[0].planned_quantity'),2+points);assert.equal(h.run('alchemyResult.targets[0].shortfall'),3-points);assert.equal(h.run('alchemyResult.complete'),false);assert(!h.get('#alchemy-result').textContent.includes('确定完成'));
    await h.run('discoverAlchemy()');assert.equal(h.run("alchemyDiscovery.recipes.find(row=>row.id==='resin').steps[0].output.quantity"),2+points);checks++;
  }
  for(const points of [3,4]){
    const h=harness();h.apply(fixture(points));let requests=0;h.context.post=async()=>{requests++;throw new Error('Invalid points must be rejected before posting');};
    await h.run('calculateAlchemy()');assert(h.get('#alchemy-error').textContent.includes('法杖保存天赋点数必须为0–2'));await h.run('discoverAlchemy()');assert.equal(requests,0);assert.equal(h.run('alchemyResult'),null);assert(h.get('#alchemy-save').disabled);
    assert.equal(h.run('validateAlchemyRaw(captureAlchemyRaw()).resources[0].state.wand_preservation'),String(points));
    const field=h.field('#alchemy-materials','法杖保存天赋点数');field.value='  '+points+'  ';await field.fire('input');const raw=plain(h.run('captureAlchemyDraft()'));h.context.draft=raw;await h.run('restoreAlchemyDraft(draft)');assert.equal(h.run('captureAlchemyDraft().raw.resources[0].state.wand_preservation'),'  '+points+'  ');assert.equal(h.run('alchemyResult'),null);checks++;
  }
  const types=harness();for(const value of [true,false,'true','false']){types.context.value=value;assert.throws(()=>types.run("alchemyStateValue('wand_preservation',value)"),/整数/);}checks++;
  const unknown=harness();unknown.apply(fixture(null));await unknown.run('calculateAlchemy()');assert.equal(unknown.run('alchemyResult.outputs[0].quantity'),null);assert.equal(unknown.run('alchemyResult.complete'),false);checks++;
  // Exercise the actual workspace handoff, then correct the historical fixed
  // inputs without losing their original record revision or saved metadata.
  const h=harness(),historical={id:'historical-resin',kind:'alchemy',name:'旧三点树脂',params:fixture(3),origin:{mode:'manual'},note:'原备注',record_revision:'e'.repeat(64)},original=plain(historical);
  h.context.opened={plan:historical,result:null,rules_changed:false,calculation_error:'法杖保存天赋点数必须为0–2的整数；未确认请留空'};
  h.context.view='workspace';h.context.planRequest=0;h.context.compareSessionUnsaved=false;h.context.manualUnsaved=false;h.context.rememberWorkspaceDetailFocus=()=>{};h.context.getJSON=async()=>h.context.opened;
  h.context.navigate=view=>{h.context.view=view;h.context.navigationSerial++;};h.context.$=selector=>['#detail-dialog','#plan-dialog'].includes(selector)?{open:false}:h.get(selector);
  const workspace=fs.readFileSync(path.join(root,'web/workspace.js'),'utf8');h.run(workspace.slice(workspace.indexOf('async function openPlan('),workspace.indexOf('\nfunction manualPayload(')));
  await h.run("openPlan('historical-resin')");assert.equal(h.run('alchemySavedPlan.record_revision'),'e'.repeat(64));assert.equal(h.run('alchemyRaw.resources[0].state.wand_preservation'),'3');assert.equal(h.run('alchemyResult'),null);assert(h.get('#alchemy-error').textContent.includes('原始输入已保留'));assert(h.get('#alchemy-save').disabled);assert(!h.get('#alchemy-result').textContent.includes('确定完成'));checks++;
  const field=h.field('#alchemy-materials','法杖保存天赋点数');field.value='2';await field.fire('input');await h.run('calculateAlchemy()');assert.equal(h.run('alchemyResult.targets[0].planned_quantity'),4);assert.equal(h.run('alchemyResult.targets[0].shortfall'),1);assert.equal(h.get('#alchemy-error').textContent,'');h.run('saveAlchemyPlan()');
  const [payload,existing]=h.saved.at(-1);assert.equal(payload.params.resources[0].state.wand_preservation,2);assert.equal(existing.record_revision,'e'.repeat(64));assert.equal(existing.note,'原备注');assert.deepEqual(historical,original);checks++;
  // Error-bearing opens use the same existing newer-edit/navigation guards.
  for(const action of ['input','navigation']){
    const editor=harness(false),pending=deferred();editor.context.loadWorkspace=()=>pending.promise;editor.context.opened={plan:historical,result:null,rules_changed:false,calculation_error:'法杖保存天赋点数必须为0–2的整数'};
    const opening=editor.run('openAlchemyPlan(opened.plan,opened.result,opened.rules_changed,opened.calculation_error)');
    if(action==='input'){editor.get('#alchemy-energy').value='17';await editor.get('#alchemy-energy').fire('input');}else editor.context.navigationSerial++;
    pending.resolve();assert.equal(await opening,false);assert.equal(editor.run('alchemySavedPlan'),null);if(action==='input')assert.equal(editor.get('#alchemy-energy').value,'17');checks++;
  }
  return checks;
}
(async()=>{
  const historyChecks=await verifyAlchemyEditHistory(),resinChecks=await verifyAlchemyResinBoundary();
  const h=harness();let checks=0;
  assert.equal(h.get('#alchemy-targets').children.length>1,true);assert.equal(h.run('alchemyFamilies.length'),73);assert.equal(new Set(metadata.families.map(row=>row.family)).size,39);checks++;
  const sword='items.weapon.melee.sword';h.apply(plan([target('recipe-stewedmeat-onemeat')],[stock(sword)],10));
  assert.equal(h.run('alchemyName("items.weapon.melee.sword")'),'单手剑');
  const identityPicker=h.field('#alchemy-materials','标准身份');
  assert(identityPicker.children.some(row=>row.value===sword&&row.textContent.includes('单手剑')&&row.textContent.includes('库存参考')));
  assert(!identityPicker.children.some(row=>row.value===sword&&row.textContent.includes('未匹配')));
  assert(h.get('#alchemy-materials').textContent.includes('不参与本版炼金配方'));
  assert(!h.get('#alchemy-resource-type').children.some(row=>row.value===sword));checks++;
  const stew=metadata.families.filter(row=>row.output==='items.food.stewedmeat'&&row.inputs);
  assert.equal(stew.length,3);assert.equal(new Set(stew.map(row=>row.name)).size,3);
  for(const row of stew){h.get('#alchemy-recipe').value=row.id;h.run('renderAlchemyEditor()');
    assert(h.get('#alchemy-formula').textContent.includes(row.cost+' 能量'));
    assert(h.get('#alchemy-formula').textContent.includes(row.quantity+' 件 / 批'));
    assert(h.get('#alchemy-recipe').children.some(option=>option.value===row.id&&option.textContent.includes(row.cost+'能量')));
    assert(h.field('#alchemy-targets','目标配方').children.some(option=>option.value===row.id&&option.textContent.includes(row.quantity+'份')));
  }
  h.apply(plan([target('recipe-meatpie')],[],10,{'items.food.stewedmeat':{recipe:stew[2].id,choices:{}}}));
  for(const row of stew)assert(h.field('#alchemy-chains','明确使用的生产配方').children.some(option=>option.value===row.id&&option.textContent.includes(row.cost+'能量')));
  assert(h.get('#alchemy-chains').textContent.includes('2 能量 → 3 件 / 批'));checks++;
  // Every real family option creates its actual choice widgets; source lists remain per instance.
  const allStock=[stock('items.wands.wandoffireblast',1,'wand',{base_level:0,cursed:false},'known'),stock('items.weapon.missiles.throwingknife',3,'missile',{tier:1,default_quantity:3,level:0,durability:75,is_upgradable:true,cursed:false}),stock('items.trinkets.ratskull',1,'trinket',{level:0}),stock('items.trinkets.trinketcatalyst',1,'catalyst',{catalyst_stage:'awaiting_choice',rolled_choices:['items.trinkets.ratskull','items.trinkets.exoticcrystals','items.trinkets.mossyclump','items.trinkets.petrifiedseed']})];
  for(const family of metadata.families){h.apply({...plan([target(family.id)],allStock),reference_version:922});for(const field of family.choices||[]){const widgets=h.walk(h.get('#alchemy-targets')).filter(row=>row.tagName==='SELECT'||row.tagName==='INPUT');if(field.type==='instance-list')assert(widgets.some(row=>row.type==='checkbox'),family.id);else assert(widgets.some(row=>row.parentNode._text.startsWith(h.run('alchemyChoiceLabels['+JSON.stringify(field.key)+']'))),family.id+' '+field.key);}}checks++;
  const precise={...plan([target('seed-potion',1,{seed_ids:['plants.blindweed$seed','plants.mageroyal$seed','plants.sungrass$seed']})],allStock),reference_version:922,chains:{'items.potions.potionoffrost':{recipe:'seed-potion',choices:{seed_ids:['plants.icecap$seed','plants.icecap$seed','plants.icecap$seed']}}}};
  h.apply(precise);const typed=plain(h.run('alchemyParams()'));assert.deepEqual(typed.targets,precise.targets);assert.deepEqual(typed.chains,precise.chains);assert.equal(typed.resources[0].origin,'known');assert.equal(typed.resources[0].state.base_level,0);assert.deepEqual(typed.resources[3].state.rolled_choices,allStock[3].state.rolled_choices);checks++;
  h.field('#alchemy-materials','现有总量（件）');const amount=h.field('#alchemy-materials','原始实例数量（件）');amount.value='2';await amount.fire('input');assert.equal(h.run('alchemyRaw.resources[0].origin'),'manual');assert.equal(h.run('alchemyRaw.targets[0].choices.seed_ids.length'),3);assert.deepEqual(plain(h.run('alchemyParams().chains')),precise.chains);checks++;
  h.apply(plan([target('resin',1,{source_keys:['w1','w2']})],[stock('items.wands.wandoffireblast',1,'w1',{base_level:-1,cursed:false}),stock('items.wands.wandoffireblast',1,'w2',{base_level:2,cursed:false})]));assert.equal(h.run('alchemyParams().resources.length'),2);assert.deepEqual(plain(h.run('alchemyParams().targets[0].choices.source_keys')),['w1','w2']);assert.equal(h.run('alchemyParams().resources[0].state.base_level'),-1);checks++;
  const catalyst=plan([target('trinket-upgrade',1,{source_key:'catalyst',target_level:3})],[allStock[3]],100,{'items.trinkets.ratskull':{recipe:'trinket-catalyst',choices:{source_key:'catalyst',selection:0}}});h.apply(catalyst);assert.deepEqual(plain(h.run('alchemyParams().targets[0].choices')),catalyst.targets[0].choices);assert.deepEqual(plain(h.run('alchemyParams().chains')),catalyst.chains);await h.run('calculateAlchemy()');assert.equal(h.run('alchemyResult.steps.length'),4);assert(h.get('#alchemy-result').textContent.includes('+2 → +3'));checks++;
  const shared=plan([target('recipe-elixiroficytouch'),target('potion-frost',1,{},'g2')],[stock('items.potions.potionoffrost')],10);h.apply(shared);await h.run('calculateAlchemy()');assert.deepEqual(plain(h.run('alchemyResult.targets.map(row=>row.planned_quantity)')),[1,0]);assert(h.get('#alchemy-copy-text').textContent.includes('缺 1 件'));assert(h.get('#alchemy-result').textContent.includes('实际消耗'));h.run('saveAlchemyPlan()');assert.deepEqual(h.saved.at(-1)[0].params,plain(h.run('alchemyResult.params')));checks++;
  const random=plan([target('seed-potion',1,{seed_ids:['plants.blindweed$seed','plants.mageroyal$seed','plants.sungrass$seed']})],[stock('plants.blindweed$seed'),stock('plants.mageroyal$seed',1,'s2'),stock('plants.sungrass$seed',1,'s3')],0);h.apply(random);await h.run('calculateAlchemy()');assert.equal(h.run('alchemyResult.outputs[0].id'),null);assert(h.get('#alchemy-result').textContent.includes('隐藏'));assert(h.get('#alchemy-copy-text').textContent.includes('随机'));checks++;
  const metal=plan([target('liquid-metal',1,{source_keys:['m']})],[stock('items.weapon.missiles.throwingknife',3,'m',{tier:1,default_quantity:3,level:0,durability:null,cursed:false,is_upgradable:true})],3);h.apply(metal);await h.run('calculateAlchemy()');assert.equal(h.run('alchemyResult.outputs[0].quantity'),null);assert(h.get('#alchemy-result').textContent.includes('条件产量'));assert.equal(h.run('alchemyParams().resources[0].state.durability'),null);checks++;
  h.apply(shared);await h.run('calculateAlchemy()');const oldResult=plain(h.run('alchemyResult'));let pending=deferred();h.context.post=async()=>pending.promise;const calculating=h.run('calculateAlchemy()');const quantity=h.field('#alchemy-targets','本次希望制作的产出（件）');quantity.value='not-an-integer';await quantity.fire('input');pending.resolve({result:oldResult});await calculating;assert.equal(h.run('alchemyRaw.targets[0].quantity'),'not-an-integer');assert(h.run('alchemyDirty'));assert.deepEqual(plain(h.run('alchemyResult')),oldResult);assert(!h.get('#alchemy-calculate').disabled);assert(h.get('#alchemy-save').disabled);checks++;
  const invalidRaw=plain(h.run('captureAlchemyRaw()'));const badDraft={raw:invalidRaw,source:{mode:'save',snapshot_at:'old-snapshot',slot:1},saved_id:'plan-original',saved_revision:'a'.repeat(64),saved_name:'原始名字',saved_origin:{mode:'save',snapshot_at:'old-snapshot',slot:1},note:'原始备注'};h.context.getJSON=async()=>({plan:{id:'plan-original',kind:'alchemy',name:'另一窗口新名字',record_revision:'b'.repeat(64),origin:{mode:'save',snapshot_at:'new-snapshot',slot:2},note:'新备注',params:shared}});h.context.draft=badDraft;await h.run('restoreAlchemyDraft(draft)');assert.equal(h.run('alchemyRaw.targets[0].quantity'),'not-an-integer');assert.equal(h.run('alchemySavedPlan.record_revision'),'a'.repeat(64));assert.equal(h.run('alchemySavedPlan.name'),'原始名字');assert.equal(h.run('alchemySavedPlan.note'),'原始备注');assert.deepEqual(plain(h.run('captureAlchemyDraft().raw')),invalidRaw);checks++;
  pending=deferred();h.context.getJSON=async()=>pending.promise;const restoring=h.run('restoreAlchemyDraft(draft)');await Promise.resolve();await Promise.resolve();const newer=h.field('#alchemy-targets','本次希望制作的产出（件）');newer.value='newer-invalid';await newer.fire('input');pending.resolve({plan:{id:'plan-original',kind:'alchemy',name:'remote',record_revision:'b'.repeat(64)}});await assert.rejects(restoring,/恢复期间/);assert.equal(h.run('alchemyRaw.targets[0].quantity'),'newer-invalid');checks++;
  // Refresh replaces each actual instance, and undo restores even invalid text and saved metadata.
  const before=plain(h.run('captureAlchemyDraft()'));h.context.post=async()=>({compatible:true,instances:[stock('items.wands.wandoffireblast',1,'wand-a',{base_level:null,cursed:false},'known'),stock('items.wands.wandoffireblast',1,'wand-b',{base_level:2,cursed:false},'known')],resources:[],energy:null,reference_version:922,source:{mode:'save',snapshot_at:'snapshot-b',slot:1}});await h.run('useAlchemyResources()');assert.equal(h.run('alchemyRaw.resources.length'),2);assert.equal(h.run('alchemyRaw.energy'),'');assert.equal(h.run('alchemyRaw.resources[0].state.base_level'),'');assert.equal(h.run('alchemyRaw.targets[0].quantity'),'newer-invalid');h.run('undoAlchemyResources()');assert.deepEqual(plain(h.run('captureAlchemyDraft()')),before);checks++;
  const reservePlan={...plan([target('resin',1,{source_keys:['wand-a']})],[stock('items.wands.wandoffireblast',1,'wand-a',{base_level:1,cursed:false},'known',1)]),reference_version:922};h.apply(reservePlan);await h.run('useAlchemyResources()');assert.equal(h.run('alchemyRaw.resources[0].reserve'),'');h.get('#alchemy-energy').value='100';assert.throws(()=>h.run('alchemyParams()'),/最低保留/);checks++;
  h.apply(reservePlan);pending=deferred();h.context.post=async()=>pending.promise;const importing=h.run('useAlchemyResources()');const reserve=h.field('#alchemy-materials','最低保留（件）');reserve.value='invalid reserve';await reserve.fire('input');pending.resolve({compatible:true,instances:[],energy:4,reference_version:922,source:{mode:'save'}});await importing;assert.equal(h.run('alchemyRaw.resources[0].reserve'),'invalid reserve');assert(h.get('#alchemy-error').textContent.includes('编辑保留'));checks++;
  h.apply(shared);h.context.post=async(url,payload)=>payload.action==='alchemy-discover'?discover(payload.params):{result:calculate(payload.params)};await h.run('discoverAlchemy()');assert.equal(h.run('alchemyDiscovery.recipes.length'),73);const candidate=plain(h.run("alchemyDiscovery.recipes.find(row=>row.id==='potion-frost')"));assert(candidate.target);const cards=h.get('#alchemy-discovery-list').children,card=cards.find(row=>row.children[0].textContent.startsWith(candidate.name+' · '));const add=h.walk(card).find(row=>row.tagName==='BUTTON');await add.fire('click');assert.equal(h.run('alchemyRaw.targets.length'),3);assert.deepEqual(plain(h.run('alchemyParams().targets[2].choices')),candidate.target.choices);assert(h.run('alchemyDirty'));assert(h.get('#alchemy-discovery-status').textContent.includes('旧库存'));checks++;
  h.apply(shared);pending=deferred();h.context.post=async()=>pending.promise;const finding=h.run('discoverAlchemy()');h.run("addAlchemyTarget('potion-healing')");pending.resolve({recipes:[],message:'stale sentinel'});await finding;assert.notEqual(h.run('alchemyDiscovery.message'),'stale sentinel');assert(!h.get('#alchemy-discover').disabled);checks++;
  const recipe=metadata.recipes.find(row=>row.id==='potion-healing'),legacy={recipe:recipe.id,recipe_version:'4.0.2',batches:2,energy:recipe.cost*2,energy_reserve:0,energy_origin:'manual',reference_version:null,resources:recipe.inputs.map(row=>({id:row.id,quantity:row.quantity*2,reserve:0,origin:'manual'}))};const resultLegacy=calculate(legacy);h.context.planLegacy={id:'legacy',name:'49配方旧计划',kind:'alchemy',params:legacy,origin:{mode:'example',snapshot_at:null,slot:null},note:'按批次',record_revision:'c'.repeat(64)};h.context.resultLegacy=resultLegacy;await h.run('openAlchemyPlan(planLegacy,resultLegacy,false)');assert.equal(h.run('alchemyParams().batches'),2);assert.equal(h.run('alchemyParams().format'),undefined);assert(h.get('#alchemy-mode').textContent.includes('旧版单配方'));h.run('saveAlchemyPlan()');assert.equal(h.saved.at(-1)[0].params.batches,2);assert.equal(h.saved.at(-1)[1].record_revision,'c'.repeat(64));h.run('convertAlchemyLegacy()');assert.equal(h.run('alchemyParams().targets[0].quantity'),2*recipe.quantity);assert.equal(h.run('alchemySavedPlan'),null);assert.equal(h.context.planLegacy.params.batches,2);checks++;
  h.context.futurePlan={...h.context.planLegacy,params:{...legacy,recipe_version:'9.0'}};await h.run('openAlchemyPlan(futurePlan,null,true)');assert.equal(h.run('alchemyParams().recipe_version'),'9.0');assert(h.get('#alchemy-status').textContent.includes('规则不同'));assert.throws(()=>h.run('convertAlchemyLegacy()'),/未核对/);checks++;
  const meta={key:'legacy',payload:{kind:'alchemy',params:legacy,source:{mode:'save',snapshot_at:'snapshot-a',slot:1},note:'原参数备注'},existing:h.context.planLegacy,name:'未提交名字',note:'未提交备注'};h.context.meta=[meta];h.run('restoreAlchemyPlanMetadata(meta)');const metaButton=h.get('#alchemy-pending-meta').children[0];await metaButton.fire('click');assert.equal(h.saved.at(-1)[1].record_revision,'c'.repeat(64));assert.equal(h.get('#plan-name').value,'未提交名字');assert.equal(h.get('#plan-note').value,'未提交备注');assert.deepEqual(plain(h.run('captureAlchemyPlanMetadata()')),[meta]);checks++;
  h.apply(shared);h.run("alchemySource={mode:'save',snapshot_at:'snapshot-a',slot:1}");const fixed=plain(h.run('captureAlchemyRaw()'));h.context.state.modified='snapshot-z';h.run('renderAlchemyOrigin()');assert(h.get('#alchemy-status').textContent.includes('快照已变化'));assert.deepEqual(plain(h.run('captureAlchemyRaw()')),fixed);checks++;
  h.context.editedMetadata=plain(metadata);h.context.editedMetadata.families[0].name+=' 新规则';h.run('initializeAlchemy(editedMetadata)');assert(h.run('alchemyRuleChanged'));assert.deepEqual(plain(h.run('captureAlchemyRaw()')),fixed);checks++;
  h.apply(shared);h.run("alchemyRaw.targets[0].key='goal-999';alchemySerial=998;renderAlchemyEditor();addAlchemyTarget('potion-healing')");assert.equal(new Set(plain(h.run('alchemyRaw.targets.map(row=>row.key)'))).size,3);checks++;
  const picker=h.get('#alchemy-resource-type');assert(picker.children.some(row=>row.value==='items.weapon.missiles.darts.adrenalinedart'));assert(!picker.children.some(row=>row.value.includes('$lightningcharge')||row.value.includes('$lotus')||row.value.endsWith('.boomerang')));assert.equal(metadata.resource_catalog.missiles.length,15);assert.equal(metadata.resource_catalog.darts.length,13);assert(!metadata.resource_catalog.missiles.some(id=>id.includes('.darts.')));checks++;
  h.apply(shared);h.context.post=async(url,payload)=>payload.action==='alchemy-discover'?discover(payload.params):{result:calculate(payload.params)};h.field('#alchemy-targets','本次希望制作的产出（件）').value='invalid target only';h.run('captureAlchemyFields()');await h.run('discoverAlchemy()');assert.equal(h.run('alchemyDiscovery.recipes.length'),73);assert.equal(h.run('alchemyRaw.targets[0].quantity'),'invalid target only');checks++;
  h.apply(plan([target('resin',1,{source_key:'w'})],[stock('items.wands.wandoffireblast',1,'w',{base_level:0,cursed:false})],5));const selected=h.walk(h.get('#alchemy-targets')).filter(row=>row.type==='checkbox');assert.equal(selected[0].checked,true);assert.deepEqual(plain(h.run('alchemyParams().targets[0].choices')),{source_key:'w'});selected[0].checked=false;await selected[0].fire('change');assert.deepEqual(plain(h.run('alchemyParams().targets[0].choices')),{});checks++;
  h.apply(shared);const first=deferred(),second=deferred();let calls=0;h.context.post=async()=>++calls===1?first.promise:second.promise;const firstCalculation=h.run('calculateAlchemy()'),secondCalculation=h.run('calculateAlchemy()');first.resolve({result:oldResult});await firstCalculation;assert(h.get('#alchemy-calculate').disabled);assert(h.run('alchemyPending'));second.resolve({result:oldResult});await secondCalculation;assert(!h.get('#alchemy-calculate').disabled);assert(!h.run('alchemyPending'));checks++;
  h.context.getJSON=async()=>{throw new Error('original removed');};h.context.draft=badDraft;await h.run('restoreAlchemyDraft(draft)');assert.equal(h.run('captureAlchemyDraft().saved_revision'),'a'.repeat(64));assert.equal(h.run('captureAlchemyDraft().saved_name'),'原始名字');checks++;
  const missileState={cursed:false,is_upgradable:true,level:0,tier:1,default_quantity:3,durability:100},extra=plan([target('recipe-telekineticgrab',8)],[stock('items.weapon.missiles.throwingstone',3,'s1',missileState),stock('items.weapon.missiles.throwingstone',3,'s2',missileState)],13);h.apply(extra);h.context.post=async(url,payload)=>({result:calculate(payload.params)});await h.run('calculateAlchemy()');const chooser=h.walk(h.get('#alchemy-result')).find(row=>row.tagName==='SELECT');assert(chooser,'multiple source paths are exposed');chooser.value='1';const choosing=h.button('#alchemy-result','明确采用此路径并重算');assert(choosing);await choosing.fire('click');assert(h.run('Object.keys(alchemyRaw.chains).length>0'));assert.equal(h.run('alchemyResult.complete'),true,h.get('#alchemy-error').textContent+' '+JSON.stringify(plain(h.run('alchemyResult.shortages'))));assert(h.get('#alchemy-copy-text').textContent.includes('明确前置路径'));checks++;
  await h.run('openAlchemyPlan(planLegacy,resultLegacy,false)');assert(h.get('#alchemy-batches').closest('label').textContent.includes('旧方案制作批次'));h.run('convertAlchemyLegacy()');assert(h.get('#alchemy-batches').closest('label').textContent.includes('新增目标产出数量'));assert(!h.get('#alchemy-recipe').required);checks++;
  // Saved plans must not replace work entered while their initial catalog is loading.
  function openingAlchemy(){
    const editor=harness(false),reads=[];
    editor.context.loadWorkspace=()=>{const pending=deferred();reads.push(pending);return pending.promise;};
    editor.context.saved={id:'saved-energy11',name:'stored energy',kind:'alchemy',origin:{mode:'example'},params:plan([target('potion-healing')],[],11)};
    return {editor,reads,open:()=>editor.run('openAlchemyPlan(saved,null,false)')};
  }
  for(const action of ['input','navigation','freeze']){
    const t=openingAlchemy(),opening=t.open();
    if(action==='input'){t.editor.get('#alchemy-energy').value='17';await t.editor.get('#alchemy-energy').fire('input');}
    else if(action==='navigation')t.editor.context.navigationSerial++;
    else t.editor.context.webEditingFrozen=true;
    t.reads[0].resolve();assert.equal(await opening,false);assert.equal(t.editor.run('alchemySavedPlan'),null);
    if(action==='input'){assert.equal(t.editor.get('#alchemy-energy').value,'17');assert(t.editor.run('alchemyDirty&&alchemyUnsaved'));}checks++;
  }
  const readyPlan=openingAlchemy(),normalOpen=readyPlan.open();readyPlan.reads[0].resolve();assert.equal(await normalOpen,true);assert.equal(readyPlan.editor.get('#alchemy-energy').value,'11');assert(!readyPlan.editor.run('alchemyDirty||alchemyUnsaved'));checks++;
  const superseded=openingAlchemy(),older=superseded.open();superseded.editor.context.saved={...superseded.editor.context.saved,id:'newer',params:plan([target('potion-healing')],[],19)};const latestAlchemyOpening=superseded.open();superseded.reads[1].resolve();assert.equal(await latestAlchemyOpening,true);superseded.reads[0].resolve();assert.equal(await older,false);assert.equal(superseded.editor.run('alchemySavedPlan.id'),'newer');assert.equal(superseded.editor.get('#alchemy-energy').value,'19');checks++;
  const unavailable=openingAlchemy();unavailable.editor.context.workspaceState={alchemy:{available:false,error:'controlled failure'}};const unavailableOpen=unavailable.open();unavailable.reads[0].resolve();assert.equal(await unavailableOpen,false);assert.equal(unavailable.editor.get('#alchemy-energy').value,'0');assert(unavailable.editor.get('#alchemy-error').textContent.includes('暂未就绪'));checks++;
  const interrupted=openingAlchemy();interrupted.editor.run('initializeAlchemy(metadata)');let failObsolete;
  interrupted.editor.context.post=()=>new Promise((resolve,reject)=>{failObsolete=reject;});const obsoleteCalculation=interrupted.editor.run('calculateAlchemy()');assert(interrupted.editor.run('alchemyPending'));assert.equal(await interrupted.open(),true);assert(!interrupted.editor.run('alchemyPending'));assert(!interrupted.editor.get('#alchemy-calculate').disabled);failObsolete(new Error('obsolete failure'));await obsoleteCalculation;assert.equal(interrupted.editor.get('#alchemy-error').textContent,'');checks++;
  console.log(JSON.stringify({passed:true,focused_component_cases:checks,history_cases:historyChecks,resin_cases:resinChecks,registered_families:39,selectable_recipes:metadata.families.length,scope:'actual alchemy JS DOM and VM, real pinned backend metadata/calculations, deferred async responses; browser/native acceptance separate'}));
})().catch(error=>{console.error(error);process.exitCode=1;});
