"""Reviewed gameplay labels and effects. This module is never shown as code in the UI."""

# label, value (a number or a Chinese discrete result), unit, condition
FIXED = {
    'items.armor.curses.bulk': [('门格内移动耗时倍率',3,'倍','站在门格时移动，无触发强度修正')],
    'items.stones.stoneofaggression': [('敌忾持续',20,'回合','首领和小首领不受影响')],
    'items.trinkets.trinketcatalyst': [('炼制能量消耗',6,'点',''),('可选项数量',4,'项','包括随机选项')],
    'items.weapon.enchantments.unstable': [('可抽到的附魔种类',14,'种','不包含延伸和水晶'),('每种附魔被抽到概率',100/14,'%','抽中后仍要满足该附魔自身的触发条件')],
    'items.armor.glyphs.brimstone': [('燃烧伤害',0,'HP','穿戴时免疫燃烧；不保护地面上的物品')],
    'items.stones.stoneofblink': [('传送目标',1,'个指定位置','同层可达位置')],
    'items.stones.stoneofflock': [('召羊半径',2,'格','仅空地，排除深渊'),('羊群初始寿命',8,'回合','逐只随机略微错开')],
    'items.stones.stoneofshock': [('电击范围',2,'格','沿可通行地形'),('麻痹',1,'回合','范围内目标')],
    'items.potions.exotic.potionofdragonsbreath': [('喷火距离',6,'格',''),('喷火角度',60,'度',''),('残废',5,'回合','受影响目标')],
    'items.spells.phaseshift': [('传送目标',1,'个','本层随机位置'),('非首领目标麻痹',10,'回合','')],
    'items.spells.wildenergy': [('立即法杖充能',1,'次/根',''),('立即神器充能强度',4,'单位','各神器转化效率不同'),('持续法杖/神器充能',8,'回合','另有随机诅咒效果')],
    'items.spells.summonelemental': [('召唤数量',1,'个元素','需要相邻空地')],
    'items.scrolls.scrolloftransmutation': [('转换对象',1,'件物品或一组投掷武器','保留等级；变成相同大类的其他种类')],
    'items.scrolls.exotic.scrollofpassage': [('传送目标',1,'个区域入口','不会传送至当前区域以外的任意指定层')],
    'items.scrolls.exotic.scrollofprismaticimage': [('虹卫数量',1,'个','已有虹卫时恢复其全部生命')],
    'items.artifacts.driedrose$petal': [('玫瑰升级',1,'级','玫瑰最高+10')],
    'items.artifacts.timekeepershourglass$sandbag': [('沙漏显示等级提升',2,'级','最高+10')],
    'items.energycrystal': [('提供炼金能量',1,'点/单位数量','大块晶体可有多个单位')],
    'items.gold': [('提供金币',1,'枚/单位数量','一堆金币可有多个单位')],
    'items.stylus': [('赋予随机刻印',1,'项','消耗1根铁笔；重新刻印会替换原刻印')],
    'items.tengusmask': [('选择专精',1,'种','可在两种职业专精中选择')],
    'items.kingscrown': [('转化英雄护甲',1,'件','保留原护甲等级与阶数')],
    'levels.traps.flocktrap': [('召羊半径',2,'格','沿可通行地形'),('羊群初始寿命',6,'回合','逐只随机略微错开')],
    'actors.buffs.lifelink': [('两者分担比例',50,'%','双方各自向上取整；多条链接按参与者平分')],
    'actors.buffs.corruption': [('阵营变为友方',100,'%','已成功施加且目标不免疫时')],
    'actors.buffs.greaterhaste': [('普通移动耗时',0,'回合','不适用于攻击或施法')],
    'actors.blobs.waterofhealth': [('恢复至最大生命',100,'%','一次性用完泉水')],
    'items.wands.wandofregrowth$seedpod': [('种子数量','2–4','颗','需相邻可放置位置')],
    'items.weapon.melee.whip.ability': [('技能命中概率',100,'%','不超力且目标没有无限闪避'),('一次消耗充能',1,'次','天赋可改变消耗')],
    'items.potions.potionofstrength': [('永久力量', 1, '点', '')],
    'items.potions.potionofexperience': [('获得经验', 1, '个完整等级的经验', '达到30级后改为祝福')],
    'items.potions.potionoffrost': [('初始覆盖', 9, '格', '中心及相邻8格，墙格除外'), ('每格冰雾量', 10, '单位', '')],
    'items.potions.potionofliquidflame': [('初始覆盖', 9, '格', '中心及相邻8格，墙格除外'), ('每格初始火焰量', 2, '单位', '')],
    'items.potions.potionoflevitation': [('投掷致眩气体量', 1000, '单位', '')],
    'items.potions.potionofparalyticgas': [('麻痹气体量', 1000, '单位', '随房间形状扩散，不是1000回合')],
    'items.potions.potionoftoxicgas': [('毒气量', 1000, '单位', '随房间形状扩散，不是1000回合')],
    'items.potions.potionofpurity': [('投掷净化距离', 3, '格', '沿可通行地形计算')],
    'items.potions.brews.blizzardbrew': [('初始气体总量', 1080, '单位', ''), ('初始覆盖', 9, '格', '中心及相邻8格；墙格的气体移到中心')],
    'items.potions.brews.infernalbrew': [('初始气体总量', 1080, '单位', ''), ('初始覆盖', 9, '格', '中心及相邻8格；墙格的气体移到中心')],
    'items.potions.brews.causticbrew': [('泼洒距离', 3, '格', '沿可通行地形计算')],
    'items.potions.brews.shockingbrew': [('电场距离', 3, '格', '沿可通行地形计算'), ('每格电场量', 20, '单位', '')],
    'items.potions.elixirs.elixiroffeatherfall': [('坠落保护时长', 50, '回合', '')],
    'items.potions.elixirs.elixirofhoneyedhealing': [('恢复饱食', 150, '点', '饮用时；另有治疗效果')],
    'items.potions.exotic.potionofmastery': [('选定装备力量需求降低', 2, '点', '每件装备只能精通一次')],
    'items.potions.exotic.potionofcleansing': [('持续净化', 5, '回合', '')],
    'items.potions.exotic.potionofdivineinspiration': [('额外天赋点', 2, '点', '选择一个天赋阶层；每阶只能获得一次')],
    'items.potions.exotic.potionofcorrosivegas': [('酸雾总量', 225, '单位', ''), ('初始覆盖', 9, '格', '中心及相邻8格')],
    'items.potions.exotic.potionofshroudingfog': [('迷雾总量', 1620, '单位', ''), ('初始覆盖', 9, '格', '中心及相邻8格')],
    'items.potions.exotic.potionofstormclouds': [('雨云总量', 1080, '单位', ''), ('初始覆盖', 9, '格', '中心及相邻8格')],
    'items.potions.exotic.potionofsnapfreeze': [('初始覆盖', 9, '格', '中心及相邻8格'), ('缠绕时长', 10, '回合', '')],
    'items.scrolls.scrollofidentify': [('完全鉴定', 1, '件物品', '')],
    'items.scrolls.scrollofmirrorimage': [('镜像数量', 2, '个', '需要相邻可生成的位置'), ('镜像生命', 1, 'HP', '')],
    'items.scrolls.scrollofrage': [('狂乱', 5, '回合', '视野内的非友军')],
    'items.scrolls.scrollofremovecurse': [('完全祛邪', 1, '件物品', '附近咒缚灵优先；对背包可处理其中物品')],
    'items.scrolls.scrollofupgrade': [('物品等级增加', 1, '级', '投掷武器对整组生效并恢复耐久')],
    'items.scrolls.scrollofmagicmapping': [('揭示本层地图', 100, '%', '不显示未见的物品或敌人')],
    'items.scrolls.scrollofteleportation': [('传送目标', 1, '个本层可达位置', '')],
    'items.scrolls.exotic.scrollofchallenge': [('竞技场伤害减免', 33, '%', '先于其他减伤结算'), ('竞技场饱食消耗', 0, '点/回合', ''), ('竞技场持续', 100, '回合', '')],
    'items.scrolls.exotic.scrollofdivination': [('随机鉴定种类', 4, '种', '未鉴定的药剂、卷轴或戒指')],
    'items.scrolls.exotic.scrollofenchantment': [('可选附魔/刻印', 3, '种', '选择其中一种')],
    'items.scrolls.exotic.scrollofmetamorphosis': [('替换天赋', 1, '项', '从其他职业提供的3种选项中选一个')],
    'items.scrolls.exotic.scrollofsirenssong': [('永久收服目标', 1, '个', '首领等可抵抗；其他听到歌声的敌人被魅惑')],
    'items.stones.stoneofaugmentation': [('影响装备', 1, '件', '')],
    'items.stones.stoneofenchantment': [('赋予随机附魔/刻印', 1, '项', '')],
    'items.stones.stoneofintuition': [('猜测未鉴定种类', 1, '种', '猜对可保留符石继续用一次')],
    'items.stones.stoneofdetectmagic': [('鉴定装备诅咒状态', 1, '件', '')],
    'items.stones.stoneofdeepsleep': [('直接伤害前睡眠时长', '无限', '', '受伤会醒；声音不会唤醒')],
    'items.spells.magicalinfusion': [('物品等级增加', 1, '级', '保留附魔/刻印')],
    'items.spells.recycle': [('转换物品', 1, '件或1组', '保留物品类型，随机变为同类其他种类')],
    'items.spells.alchemize': [('出售/分解次数', 1, '次/枚', '')],
    'items.spells.reclaimtrap': [('可储存陷阱', 1, '个', '')],
    'items.spells.telekineticgrab': [('远程拾取', 1, '堆物品/枚', '')],
    'items.spells.beaconofreturning': [('同时记录地点', 1, '个', '')],
    'items.keys.goldenkey': [('开启宝箱', 1, '个/把', '')],
    'items.keys.crystalkey': [('开启水晶锁', 1, '个/把', '')],
    'items.keys.ironkey': [('开启铁锁', 1, '个/把', '')],
    'items.keys.wornkey': [('开启相应任务锁', 1, '个/把', '')],
    'items.bags.velvetpouch': [('收纳容量', 19, '格', '种子与符石；袋子占主背包1格')],
    'items.bags.scrollholder': [('收纳容量', 19, '格', '卷轴与菱晶；袋子占主背包1格')],
    'items.bags.potionbandolier': [('收纳容量', 19, '格', '药剂；袋子占主背包1格')],
    'items.bags.magicalholster': [('收纳容量', 19, '格', '法杖与投掷武器'), ('法杖充能时间倍率', 0.85, '倍', ''), ('投掷武器耐久倍率', 1.2, '倍', '')],
    'plants.blandfruitbush': [('产出无味果', 1, '个', '')],
    'plants.fadeleaf': [('守望者返回', 1, '层', '允许跨层传送时；其他职业在本层传送')],
    'plants.rotberry': [('普通毒气量', 100, '单位', ''), ('守望者力量增益', 1, '点', '替代毒气')],
    'plants.swiftthistle': [('瞬间行动额度', 6, '回合', '攻击或施法会提前结束'), ('守望者额外极速', 1, '回合', '')],
    'plants.swiftthistle$timebubble': [('瞬间行动额度', 6, '回合', '攻击或施法会提前结束')],
    'actors.buffs.bless': [('命中倍率', 1.25, '倍', ''), ('闪避倍率', 1.25, '倍', '')],
    'actors.buffs.hex': [('命中倍率', 0.8, '倍', ''), ('闪避倍率', 0.8, '倍', '')],
    'actors.buffs.doom': [('受到伤害倍率', 2, '倍', '不包括免疫的伤害来源')],
    'actors.buffs.vulnerable': [('受到物理伤害倍率', 1.33, '倍', '')],
    'actors.buffs.weakness': [('物理伤害倍率', 0.67, '倍', '')],
    'actors.buffs.cripple': [('移动速度倍率', 0.5, '倍', '')],
    'actors.buffs.haste': [('移动速度倍率', 3, '倍', '不加速攻击或施法')],
    'actors.buffs.stamina': [('移动速度倍率', 1.5, '倍', '')],
    'actors.buffs.slow': [('动作速度倍率', 0.5, '倍', '')],
    'actors.buffs.speed': [('动作速度倍率', 2, '倍', '')],
    'actors.buffs.adrenaline': [('攻击速度倍率', 1.5, '倍', ''), ('移动速度倍率', 2, '倍', '')],
    'actors.buffs.fury': [('物理伤害倍率', 1.5, '倍', '')],
    'actors.buffs.hunger': [('开始饥饿', 300, '点', ''), ('开始饿损', 450, '点', ''), ('通常饱食消耗', 1, '点/回合', '')],
    'actors.buffs.magicimmune': [('受魔法影响', 0, '%', '英雄护甲技能等强效能力可例外')],
    'actors.buffs.invulnerability': [('可免疫的伤害', 100, '%', '')],
    'actors.buffs.paralysis': [('可主动行动', 0, '次', '持续期内')],
    'actors.buffs.frost': [('可主动行动', 0, '次', '受伤会解除冻结')],
    'mechanics.drops': [('每5层力量药剂', 2, '瓶', '常规主地牢'), ('每5层升级卷轴', 3, '张', '禁忌符文减半'), ('通常主地牢层数', 26, '层', '')],
    'mechanics.regeneration': [('通常恢复', 1, 'HP/10回合', '未饿损且允许自然恢复'), ('通常饱食消耗', 1, '点/回合', '')],
    'mechanics.saving': [('自动备份检查间隔', 10, '秒', '现实时间；只能捕获游戏已保存的状态')],
}

# The amount is obtained from the named buff, not copied from a text description.
DURATION_EFFECTS = {
    'items.torch': [('照明','Light',1,'')],
    'items.stones.stoneoffear': [('恐惧','Terror',1,'非友方目标')],
    'items.potions.potionofhaste': [('极速', 'Haste', 1, '')],
    'items.potions.potionofinvisibility': [('隐形', 'Invisibility', 1, '攻击/施法提前结束')],
    'items.potions.potionoflevitation': [('浮空', 'Levitation', 1, '饮用时')],
    'items.potions.potionofmindvision': [('灵视', 'MindVision', 1, '')],
    'items.potions.potionofpurity': [('环境免疫', 'BlobImmunity', 1, '饮用时')],
    'items.potions.elixirs.elixirofdragonsblood': [('烈焰之力', 'FireImbue', 1, '')],
    'items.potions.elixirs.elixiroficytouch': [('寒霜之力', 'FrostImbue', 1, '')],
    'items.potions.elixirs.elixiroftoxicessence': [('毒性之力', 'ToxicImbue', 1, '')],
    'items.potions.exotic.potionofstamina': [('精力回复', 'Stamina', 1, '')],
    'items.potions.exotic.potionofmagicalsight': [('魔能透视', 'MagicalSight', 1, '')],
    'items.scrolls.scrolloflullaby': [('进入睡眠前催眠', 'Drowsy', 1, '')],
    'items.scrolls.scrollofrecharging': [('法杖充能', 'Recharging', 1, '')],
    'items.scrolls.scrollofterror': [('恐惧', 'Terror', 1, '受攻击会缩短')],
    'items.scrolls.exotic.scrollofantimagic': [('魔法免疫', 'MagicImmune', 1, '')],
    'items.scrolls.exotic.scrollofforesight': [('先见', 'Foresight', 1, '')],
    'items.scrolls.exotic.scrollofmysticalenergy': [('神器充能', 'ArtifactRecharge', 1, '')],
    'items.scrolls.exotic.scrollofdread': [('梦魇', 'Dread', 1, '离开视野后消失')],
    'plants.blindweed': [('致盲', 'Blindness', 1, '普通目标'), ('残废', 'Cripple', 1, '普通目标'), ('隐形', 'Invisibility', 0.5, '守望者替代效果')],
    'plants.mageroyal': [('环境免疫', 'BlobImmunity', 0.5, '守望者额外效果')],
    'plants.firebloom': [('烈焰之力', 'FireImbue', 0.3, '守望者额外效果')],
    'plants.icecap': [('寒霜之力', 'FrostImbue', 0.3, '守望者额外效果')],
    'plants.sorrowmoss': [('毒性之力', 'ToxicImbue', 0.3, '守望者额外效果')],
    'plants.starflower': [('赐福', 'Bless', 1, ''), ('法杖充能', 'Recharging', 1, '守望者额外效果')],
    'plants.stormvine': [('眩晕', 'Vertigo', 1, '普通目标'), ('浮空', 'Levitation', 0.5, '守望者替代效果')],
}

TRINKETS = {
    'chaoticcenser': [('平均喷气间隔', '300 / (L+1)', '回合')],
    'crackedspyglass': [('额外幻影掉落概率', '.375*(L+1)*100', '%')],
    'dimensionalsundial': [('白天敌人生成速度', '(.95-.05*L)*100', '%'), ('夜间敌人生成速度', '(1.25+.25*L)*100', '%')],
    'exoticcrystals': [('药剂/卷轴变为炼金变种概率', '(.2+.2*L)*100', '%')],
    'eyeofnewt': [('正常视距保留', '(.875-.125*L)*100', '%'), ('灵视距离', '2+L', '格')],
    'ferrettuft': [('闪避倍率', '1+.125*(L+1)', '倍')],
    'mimictooth': [('宝箱怪概率倍率', '1.5+.5*L', '倍'), ('乌木宝箱怪概率', '(.125+.125*L)*100', '%')],
    'mossyclump': [('草地/水面楼层概率', '(.25+.25*L)*100', '%')],
    'parchmentscrap': [('附魔概率倍率', [2,4,7,10], '倍'), ('诅咒概率倍率', [1.5,2,1,0], '倍')],
    'petrifiedseed': [('种子掉落转为符石概率', [25,46,65,80], '%'), ('草地掉落倍率', '1+.25*L/3.0', '倍')],
    'ratskull': [('稀有敌人概率倍率', '2+L', '倍')],
    'saltcube': [('饱食消耗倍率', '1.0/(1+.25*(L+1))', '倍'), ('自然恢复速率', [84,73,66,60], '%')],
    'shardofoblivion': [('可计入的未知物品上限', 'L+1', '件'), ('满额掉落倍率', '1+.2*(L+1)', '倍')],
    'thirteenleafclover': [('伤害改为最大值概率', '(.25+.25*L)*60', '%'), ('伤害改为最小值概率', '(.25+.25*L)*40', '%')],
    'trapmechanism': [('陷阱楼层概率', '(.25+.25*L)*100', '%'), ('隐藏陷阱揭示概率', '(.1+.1*L)*100', '%')],
    'vialofblood': [('总治疗倍率', '1+.125*(L+1)', '倍')],
    'wondrousresin': [('诅咒法杖效果转正概率', '(.25+.25*L)*100', '%'), ('额外诅咒法杖效果概率', '(.125+.125*L)*100', '%')],
}
