'use strict';
// Original strings are retained until an explicit calculation builds typed parameters.
let alchemyRecipes=[],alchemyFamilies=[],alchemyCatalog={items:[]},alchemyInitialized=false;
let alchemyDirty=false,alchemyUnsaved=false,alchemyPending=false,alchemyRequest=0,alchemyGeneration=0,alchemyPendingRequest=0,alchemyOpenRequest=0;
let alchemyResult=null,alchemySavedPlan=null,alchemySource={mode:'example',snapshot_at:null,slot:null},alchemyUndo=null,alchemyRuleChanged=false;
let alchemyDiscovery=null,alchemyDiscoveryGeneration=-1,alchemyDiscoveryRequest=0,alchemyDiscoveryPendingRequest=0,alchemySerial=0,alchemyControls=[],alchemyProducerButtons=[];
let alchemyRaw={format:2,recipe_version:'4.0.2',targets:[],resources:[],energy:'0',energy_reserve:'0',energy_origin:'manual',reference_version:null,chains:{}};
const alchemyPlanMetadata=new Map(),alchemyClone=value=>JSON.parse(JSON.stringify(value));
const alchemyStateLabels={cooked:'生熟状态',potion_id:'熟果效果',cursed:'诅咒状态',is_upgradable:'可升级资格',base_level:'法杖基础等级',public_level:'公开显示等级',resin_bonus:'树脂附加等级',hero_class:'角色职业',wand_preservation:'法杖保存天赋点数',level:'物品等级',tier:'投武阶数',default_quantity:'此种类默认堆数',durability:'精确耐久假设（0–100）',catalyst_stage:'触媒付费与选择阶段',rolled_choices:'已经显示的四个选项'};
const alchemyChoiceLabels={source_key:'指定原物品 / 原始堆',source_keys:'明确消耗的完整实例',selection:'已显示四选项中的选择',target_level:'目标饰物等级',seed_id:'所用种子',seed_ids:'三个种子槽',ingredient_id:'炸弹增强材料',potion_id:'所用药剂',scroll_id:'所用卷轴',stone_id:'所用符石',pasty_id:'肉馅饼 / 幻影鱼肉',meat_id:'所用肉类'};
const alchemyEnums={cooked:[['raw','未熟原果'],['cooked','已经烹煮'],['unknown','尚未确认']],cursed:[['false','已确认无诅咒'],['true','已确认有诅咒']],is_upgradable:[['true','已确认可以升级'],['false','不可升级']],hero_class:[['WARRIOR','战士'],['MAGE','法师'],['ROGUE','盗贼'],['HUNTRESS','女猎手'],['DUELIST','决斗家'],['CLERIC','牧师']],catalyst_stage:[['unrolled','尚未付费 / 未生成选项'],['awaiting_choice','已经付费，等待四选']]};
const alchemyText=value=>value==null?'':String(value),alchemyHTML=value=>escapeHTML(alchemyText(value));
function alchemyName(id){return alchemyCatalog.items.find(row=>row.id===id)?.name||alchemyCatalog.known_names?.[id]||alchemyRecipes.find(row=>row.output===id)?.name||id||'身份未确定';}
function alchemyFamily(id){return alchemyFamilies.find(row=>row.id===id);}
function alchemyRecipeDescription(row){return row?.inputs?row.inputs.map(input=>alchemyName(input.id)+' ×'+input.quantity).join(' + ')+' + '+row.cost+' 能量 → '+row.quantity+' 件 / 批':row?.requirements?.join('；')||'此配方当前未收录，原条件保留。';}
function alchemyRecipe(){return alchemyRecipes.find(row=>row.id===$('#alchemy-recipe')?.value);}
function alchemyNumber(value,label,signed=false){if(typeof value!=='string'||!(signed?/^-?\d+$/:/^\d+$/).test(value.trim()))throw new Error(label+'请填写整数；空白或无效输入尚未计算');const n=Number(value);if(!Number.isSafeInteger(n)||n<(signed?-2147483648:0)||n>2147483647)throw new Error(label+'超出游戏整数范围');return n;}
function alchemyNode(tag,text='',className=''){const node=document.createElement(tag);if(text)node.textContent=text;if(className)node.className=className;return node;}
function alchemyButton(text,action){const button=alchemyNode('button',text,'secondary');button.type='button';button.addEventListener('click',()=>{try{const pending=action();if(pending?.catch)return pending.catch(error=>inlineError($('#alchemy-error'),error.message));}catch(error){inlineError($('#alchemy-error'),error.message);}});return button;}
function alchemyOptions(select,items,value,empty='尚未明确选择'){
  select.replaceChildren();const option=alchemyNode('option',empty);option.value='';select.append(option);const rows=items.map(row=>Array.isArray(row)?row:[row.id,row.name]);
  if(value!==''&&value!=null&&!rows.some(row=>row[0]===String(value)))rows.unshift([String(value),alchemyCatalog.known_names?.[value]?alchemyName(value)+'（已知物品，仅作库存参考）':'原选择：'+String(value)+'（当前列表未匹配）']);
  for(const [id,name] of rows){const item=alchemyNode('option',name);item.value=id;select.append(item);}select.value=alchemyText(value);
}
function alchemyField(parent,label,value,setter,options=null,refresh=null){
  const wrap=alchemyNode('label',label),input=alchemyNode(options?'select':'input');
  if(options)alchemyOptions(input,options,value);else{input.type='text';input.inputMode='decimal';input.maxLength=200;input.value=alchemyText(value);}
  input.alchemyRead=()=>setter(input.value);alchemyControls.push(input);input.addEventListener(options?'change':'input',()=>{input.alchemyRead();alchemyChanged();if(refresh)refresh();});wrap.append(input);parent.append(wrap);return input;
}
function ensureAlchemyEditor(){
  const form=$('#alchemy-form');if(!form||$('#alchemy-targets'))return;
  const mode=alchemyNode('p');mode.id='alchemy-mode';mode.className='rule-warning';mode.setAttribute('role','status');form.prepend(mode);
  const actions=alchemyNode('div','','form-actions');actions.id='alchemy-target-actions';actions.append(alchemyButton('添加这个产出目标',()=>addAlchemyTarget($('#alchemy-recipe').value,$('#alchemy-batches').value)),alchemyButton('以产出目标编辑副本',convertAlchemyLegacy));form.insertBefore(actions,$('#alchemy-materials'));
  for(const id of ['alchemy-targets','alchemy-chains']){const node=alchemyNode('section');node.id=id;node.tabIndex=-1;node.setAttribute('aria-label',id==='alchemy-targets'?'产出目标与材料选择':'前置生产路径');form.insertBefore(node,$('#alchemy-materials'));}
  const discovery=alchemyNode('section','','panel workspace-section');discovery.id='alchemy-discovery';discovery.append(alchemyNode('h2','按当前库存发现候选'),alchemyNode('p','每项使用同一库存副本独立预览，并不穷尽所有材料组合；候选不能同时占用同一份资源。加入目标后重新计算共同账本。','muted'));
  const button=alchemyButton('预览当前资源的配方候选',discoverAlchemy);button.id='alchemy-discover';discovery.append(button);const status=alchemyNode('p');status.id='alchemy-discovery-status';status.setAttribute('role','status');discovery.append(status);const list=alchemyNode('div');list.id='alchemy-discovery-list';discovery.append(list);form.parentNode.insertBefore(discovery,form.nextSibling);
}
function initializeAlchemy(data){
  if(!$('#alchemy-form'))return;ensureAlchemyEditor();if(data?.available===false){inlineError($('#alchemy-error'),data.error);return;}if(!data?.recipes?.length)return;
  const signature=JSON.stringify([data.recipes,data.families,data.resource_catalog]),changed=alchemyInitialized&&signature!==initializeAlchemy.signature;
  alchemyRecipes=alchemyClone(data.recipes);alchemyFamilies=alchemyClone(data.families||data.recipes.map(row=>({...row,choices:[],mode:'stack',possible_outputs:[row.output]})));alchemyCatalog=alchemyClone(data.resource_catalog||{items:[]});
  if(!alchemyInitialized){alchemyInitialized=true;alchemyRaw.targets=[{key:'goal-1',recipe:'potion-healing',quantity:'1',choices:{}}];alchemySerial=1;renderAlchemyEditor();renderAlchemyResult();}
  else if(changed){alchemyRuleChanged=true;alchemyChanged();renderAlchemyEditor();}initializeAlchemy.signature=signature;renderAlchemyOrigin();
}
async function loadAlchemy(){try{if(!alchemyInitialized)await loadWorkspace();initializeAlchemy(workspaceState?.alchemy);}catch(error){inlineError($('#alchemy-error'),error.message);}}
function captureAlchemyFields(){for(const input of alchemyControls)if(input.isConnected!==false)input.alchemyRead();alchemyRaw.energy=$('#alchemy-energy').value;alchemyRaw.energy_reserve=$('#alchemy-energy-reserve').value;if(alchemyRaw.format!==2){alchemyRaw.recipe=$('#alchemy-recipe').value;alchemyRaw.batches=$('#alchemy-batches').value;}}
function captureAlchemyRaw(){captureAlchemyFields();return {...alchemyClone(alchemyRaw),picker_recipe:$('#alchemy-recipe').value,picker_quantity:$('#alchemy-batches').value};}
function alchemyStateValue(name,value){
  if(value==null||value==='')return null;
  if(name==='rolled_choices'){if(value.every(item=>item===''))return null;if(value.length!==4||value.some(item=>!item))throw new Error('已经显示的触媒选项需完整登记四项；未显示时请全部留空');return [...value];}
  if(name==='cursed'||name==='is_upgradable'){if(value==='true'||value===true)return true;if(value==='false'||value===false)return false;throw new Error(alchemyStateLabels[name]+'未明确');}
  if(alchemyEnums[name]||name==='potion_id')return value;
  if(name==='durability'){if(typeof value!=='string'||!/^\d+(?:\.\d+)?$/.test(value.trim())||!Number.isFinite(Number(value))||Number(value)>100)throw new Error('精确耐久需为0–100的明确手填有限数值');return Number(value);}
  return alchemyNumber(value,alchemyStateLabels[name]||name,['level','base_level','public_level'].includes(name));
}
function alchemyTypedChoices(raw){const output={};for(const [name,value] of Object.entries(raw)){if(value==null||value===''||Array.isArray(value)&&!value.length)continue;if(name==='selection'||name==='target_level')output[name]=alchemyNumber(value,alchemyChoiceLabels[name]);else if(Array.isArray(value)){if(value.every(item=>item===''))continue;if(value.some(item=>!item))throw new Error(alchemyChoiceLabels[name]+'请选齐，或全部留空保留为待选择');output[name]=[...value];}else output[name]=value;}return output;}
function alchemyParams(includeTargets=true){
  captureAlchemyFields();const raw=alchemyRaw,shared={recipe_version:raw.recipe_version||'4.0.2',energy:alchemyNumber(raw.energy,'本次可支配总能量'),energy_reserve:alchemyNumber(raw.energy_reserve,'最低保留能量'),energy_origin:raw.energy_origin,reference_version:raw.reference_version};
  if(raw.format!==2)return {...shared,recipe:raw.recipe,batches:alchemyNumber(raw.batches,'旧方案批次'),resources:raw.resources.map(row=>({id:row.id,quantity:alchemyNumber(row.quantity,alchemyName(row.id)+'总量'),reserve:alchemyNumber(row.reserve,'最低保留'),origin:row.origin}))};
  return {...shared,format:2,targets:includeTargets?raw.targets.map(row=>({key:row.key,recipe:row.recipe,quantity:alchemyNumber(row.quantity,'目标产出数量'),choices:alchemyTypedChoices(row.choices)})):[],resources:raw.resources.map(row=>({key:row.key,id:row.id,quantity:alchemyNumber(row.quantity,alchemyName(row.id)+'实例数量'),reserve:alchemyNumber(row.reserve,'实例最低保留'),origin:row.origin,state:Object.fromEntries(Object.entries(row.state).map(([name,value])=>[name,alchemyStateValue(name,value)]))})),chains:Object.fromEntries(Object.entries(raw.chains).map(([id,row])=>[id,{recipe:row.recipe,choices:alchemyTypedChoices(row.choices)}]))};
}
function alchemyChanged(){alchemyGeneration++;alchemyRequest++;alchemyDiscoveryRequest++;alchemyDirty=true;alchemyUnsaved=true;for(const button of alchemyProducerButtons)button.disabled=true;renderAlchemyOrigin();if($('#alchemy-stale'))$('#alchemy-stale').hidden=false;renderAlchemyDiscovery();}
function alchemySelectedInstances(field,family){let allowed=alchemyCatalog[field.group]||[];if(family.id==='trinket-upgrade')allowed=[...allowed,...(alchemyCatalog.catalyst||[])];return alchemyRaw.resources.filter(row=>allowed.includes(row.id)).map(row=>[row.key,alchemyName(row.id)+' · '+row.key]);}
function renderAlchemyChoices(parent,family,selection){
  if(!family?.choices?.length)return;const grid=alchemyNode('div','','form-grid');parent.append(grid);
  for(const field of family.choices){const name=field.key,label=alchemyChoiceLabels[name]||name;
    if(field.type==='instance-list'){
      const box=alchemyNode('fieldset');box.append(alchemyNode('legend',label+'（整根 / 整堆全部消耗）'));const available=alchemySelectedInstances(field,family),selected=selection[name]||(selection.source_key?[selection.source_key]:[]);
      for(const old of selected)if(!available.some(row=>row[0]===old))available.push([old,'原实例 '+old+'（当前库存没有匹配）']);if(!available.length)box.append(alchemyNode('p','请先添加或明确带入对应库存实例。','muted'));
      for(const [id,text] of available){const labelNode=alchemyNode('label',text,'check-inline'),input=alchemyNode('input');input.type='checkbox';input.checked=selected.includes(id);input.alchemyRead=()=>{const values=new Set(selection[name]||(selection.source_key?[selection.source_key]:[]));if(values.has(id)!==input.checked){input.checked?values.add(id):values.delete(id);selection[name]=Array.from(values);delete selection.source_key;}};alchemyControls.push(input);input.addEventListener('change',()=>{input.alchemyRead();alchemyChanged();});labelNode.prepend(input);box.append(labelNode);}grid.append(box);
    }else if(field.type==='three-items'){for(let index=0;index<3;index++)alchemyField(grid,label+' '+(index+1),selection[name]?.[index]||'',value=>{if((selection[name]?.[index]??'')!==value){selection[name]??=['','',''];selection[name][index]=value;}},(field.allowed||[]).map(id=>[id,alchemyName(id)]));}
    else{const options=field.type==='instance'?alchemySelectedInstances(field,family):field.type==='selection'?[['0','第1项'],['1','第2项'],['2','第3项'],['3','第4项']]:field.type==='level'?[['1','+1'],['2','+2'],['3','+3']]:(field.allowed||[]).map(id=>[id,alchemyName(id)]);alchemyField(grid,label,selection[name]??'',value=>{if((selection[name]??'')!==value)selection[name]=value;},options);}
  }
  if(family.id==='trinket-catalyst')parent.append(alchemyNode('p','下标只对应原触媒已经显示的四项；未生成选项不能预定饰物。已付费四选不重复支付6能量。','muted'));
  if(family.id==='trinket-upgrade')parent.append(alchemyNode('p','升级数量为1件特定饰物。若来源是已付费触媒，请在“前置生产路径”中先指定其已经显示的饰物选项；逐级独立收费。','muted'));
}
function addAlchemyTarget(id,quantity='1',selection={}){captureAlchemyFields();if(alchemyRaw.format!==2)throw new Error('旧方案使用批次语义；请先明确以产出目标编辑副本');if(!alchemyFamily(id))throw new Error('请选择已核对配方');if(alchemyRaw.targets.length>=64)throw new Error('最多64个目标');let key;do{key='goal-'+(++alchemySerial);}while(alchemyRaw.targets.some(row=>row.key===key));alchemyRaw.targets.push({key,recipe:id,quantity:alchemyText(quantity),choices:alchemyRawChoices(selection)});alchemyChanged();renderAlchemyEditor();$('#alchemy-targets').focus();}
function renderAlchemyTargets(){
  const root=$('#alchemy-targets');root.replaceChildren();root.hidden=alchemyRaw.format!==2;if(root.hidden)return;root.append(alchemyNode('h2','按产出规划 · 目标顺序就是优先级'),alchemyNode('p','数量是本次制作并保留给这个目标的件数；不是批次或最终拥有总量。已认领成品不会再次供给其他目标。','muted'));
  for(const [index,row] of alchemyRaw.targets.entries()){const card=alchemyNode('fieldset');card.append(alchemyNode('legend','目标 '+(index+1)+' · '+row.key));const grid=alchemyNode('div','','form-grid');card.append(grid);alchemyField(grid,'目标配方',row.recipe,value=>{if(row.recipe!==value){row.recipe=value;row.choices={};}},alchemyFamilies.map(f=>[f.id,f.name+(f.group?' · '+f.group:'')]),renderAlchemyEditor);alchemyField(grid,'本次希望制作的产出（件）',row.quantity,value=>row.quantity=value);
    const family=alchemyFamily(row.recipe);card.append(alchemyNode('p',alchemyRecipeDescription(family),'muted'));renderAlchemyChoices(card,family,row.choices);const actions=alchemyNode('div','','form-actions');
    for(const [text,offset] of [['上移',-1],['下移',1]]){const button=alchemyButton(text,()=>{captureAlchemyFields();const other=index+offset;[alchemyRaw.targets[index],alchemyRaw.targets[other]]=[alchemyRaw.targets[other],alchemyRaw.targets[index]];alchemyChanged();renderAlchemyEditor();});button.disabled=index+offset<0||index+offset>=alchemyRaw.targets.length;actions.append(button);}actions.append(alchemyButton('移除此目标',()=>{captureAlchemyFields();alchemyRaw.targets.splice(index,1);alchemyChanged();renderAlchemyEditor();}));card.append(actions);root.append(card);
  }if(!alchemyRaw.targets.length)root.append(alchemyNode('p','尚无目标。选择上方配方，再添加一个产出目标。','muted'));
}
function alchemyResourceState(parent,row){
  const meta=alchemyCatalog.items.find(item=>item.id===row.id),fields=Array.from(new Set([...(meta?.state_fields||[]),...Object.keys(row.state)]));if(!fields.length)return;const details=alchemyNode('details');details.append(alchemyNode('summary','物品状态与未确认条件'));const grid=alchemyNode('div','','form-grid');details.append(grid);const set=(name,value)=>{if(JSON.stringify(row.state[name]??'')!==JSON.stringify(value)){row.state[name]=value;row.origin='manual';}};
  for(const name of fields){if(name==='rolled_choices'){for(let index=0;index<4;index++)alchemyField(grid,'已经显示的触媒选项 '+(index+1),row.state[name]?.[index]||'',value=>{if((row.state[name]?.[index]??'')!==value)set(name,(row.state[name]||['','','','']).map((v,i)=>i===index?value:v));},[...(alchemyCatalog.trinkets||[]),'items.trinkets.trinketcatalyst$randomtrinket'].map(id=>[id,id.endsWith('$randomtrinket')?'随机饰物（身份不确定）':alchemyName(id)]));}else alchemyField(grid,alchemyStateLabels[name]||name,row.state[name]??'',value=>set(name,value),alchemyEnums[name]||(name==='potion_id'?(alchemyCatalog.potions||[]).filter(id=>!id.includes('.exotic.')).map(id=>[id,alchemyName(id)]):null));}
  details.append(alchemyNode('p','留空表示未知，不能当成0或无诅咒。修改状态后这个实例成为明确手填假设；精确投武耐久必须手填。法杖基础等级与公开等级/树脂须一致。','muted'));parent.append(details);
}
function addAlchemyResource(id){captureAlchemyFields();if(alchemyRaw.format!==2)throw new Error('逐实例资源请在目标模式中编辑');if(!id)throw new Error('请选择材料身份');if(alchemyRaw.resources.length>=256)throw new Error('库存实例最多256项');let key;do{key='manual-'+(++alchemySerial);}while(alchemyRaw.resources.some(row=>row.key===key));alchemyRaw.resources.push({key,id,quantity:'1',reserve:'0',origin:'manual',state:{}});alchemyChanged();renderAlchemyEditor();}
function renderAlchemyMaterials(){
  const root=$('#alchemy-materials');if(!root||!alchemyInitialized)return;root.replaceChildren();const legacy=alchemyRaw.format!==2;root.append(alchemyNode('h2',legacy?'旧方案材料总量':'同一份库存 · 原始实例与最低保留'),alchemyNode('p',legacy?'这个旧方案按同身份总量与批次计算；需要状态或多目标时，请明确转换副本。':'每行是一件原物品或一个原始堆。相同身份但等级、耐久、生熟或来源不同，不能合并；同一实际堆不能重复登记。','muted'));
  if(!legacy){const add=alchemyNode('div','','form-grid'),label=alchemyNode('label','添加明确手填的物品 / 原始堆'),select=alchemyNode('select');select.id='alchemy-resource-type';alchemyOptions(select,alchemyCatalog.items,'','请选择标准身份');label.append(select);add.append(label,alchemyButton('添加一个独立实例',()=>addAlchemyResource(select.value)));root.append(add);}
  for(const row of alchemyRaw.resources){const card=alchemyNode('fieldset');card.append(alchemyNode('legend',alchemyName(row.id)+(row.key?' · '+row.key:'')));const grid=alchemyNode('div','','form-grid');card.append(grid);if(!legacy&&!alchemyCatalog.items.some(item=>item.id===row.id)&&alchemyCatalog.known_names?.[row.id])card.append(alchemyNode('p','此已知物品仅作库存参考，不参与本版炼金配方；计算不会消耗它。','muted'));if(!legacy)alchemyField(grid,'标准身份',row.id,value=>{if(row.id!==value){row.id=value;row.state={};row.origin='manual';}},alchemyCatalog.items,renderAlchemyEditor);alchemyField(grid,legacy?'现有总量（件）':'原始实例数量（件）',row.quantity,value=>{if(row.quantity!==value){row.quantity=value;row.origin='manual';}});alchemyField(grid,'最低保留（件）',row.reserve,value=>row.reserve=value);const origin=alchemyNode('p','','muted');origin.setAttribute('data-alchemy-origin',row.key||row.id);card.append(origin);if(!legacy){alchemyResourceState(card,row);card.append(alchemyButton('移除此库存实例',()=>{captureAlchemyFields();alchemyRaw.resources=alchemyRaw.resources.filter(item=>item!==row);alchemyChanged();renderAlchemyEditor();}));}root.append(card);}if(!alchemyRaw.resources.length)root.append(alchemyNode('p','尚未登记库存；可以明确带入已知实例，或逐项手填。','muted'));
}
function renderAlchemyChains(){
  const root=$('#alchemy-chains');root.replaceChildren();root.hidden=alchemyRaw.format!==2;if(root.hidden)return;root.append(alchemyNode('h2','前置生产路径'),alchemyNode('p','先用库存，再补前置材料。唯一确定路径可自动展开；多个配方或材料选择需明确指定。随机结果不能假装是下一步材料。','muted'));
  const add=alchemyNode('div','','form-grid'),label=alchemyNode('label','需要前置生产的标准产物'),select=alchemyNode('select');select.id='alchemy-chain-output';alchemyOptions(select,alchemyCatalog.items.filter(row=>alchemyFamilies.some(f=>f.possible_outputs?.includes(row.id))),'');label.append(select);add.append(label,alchemyButton('添加前置路径选择',()=>{captureAlchemyFields();const id=select.value;if(!id)throw new Error('请选择前置产物');if(Object.keys(alchemyRaw.chains).length>=256)throw new Error('前置选择最多256项');if(alchemyRaw.chains[id])throw new Error('这个产物已有前置选择，请在下方编辑');const first=alchemyFamilies.find(f=>f.possible_outputs?.includes(id));alchemyRaw.chains[id]={recipe:first?.id||'',choices:{}};alchemyChanged();renderAlchemyEditor();}));root.append(add);
  for(const [id,row] of Object.entries(alchemyRaw.chains)){const card=alchemyNode('fieldset');card.append(alchemyNode('legend','前置产物：'+alchemyName(id)));const grid=alchemyNode('div','','form-grid');card.append(grid);alchemyField(grid,'明确使用的生产配方',row.recipe,value=>{if(row.recipe!==value){row.recipe=value;row.choices={};}},alchemyFamilies.filter(f=>f.possible_outputs?.includes(id)).map(f=>[f.id,f.name]),renderAlchemyEditor);card.append(alchemyNode('p',alchemyRecipeDescription(alchemyFamily(row.recipe)),'muted'));renderAlchemyChoices(card,alchemyFamily(row.recipe),row.choices);card.append(alchemyButton('恢复自动路径 / 删除此选择',()=>{captureAlchemyFields();delete alchemyRaw.chains[id];alchemyChanged();renderAlchemyEditor();}));root.append(card);}
}
function renderAlchemyEditor(){
  if(!alchemyInitialized)return;alchemyControls=[];const legacy=alchemyRaw.format!==2,selected=legacy?alchemyRaw.recipe:$('#alchemy-recipe').value||'potion-healing';alchemyOptions($('#alchemy-recipe'),(legacy?alchemyRecipes:alchemyFamilies).map(row=>[row.id,row.name+(row.group?' · '+row.group:'')]),selected,'请选择配方');$('#alchemy-recipe').required=legacy;$('#alchemy-batches').required=legacy;const batchLabel=$('#alchemy-batches').closest('label')?.firstChild;if(batchLabel?.nodeType===3)batchLabel.nodeValue=legacy?'旧方案制作批次（次）':'新增目标产出数量（件）';$('#alchemy-energy').value=alchemyRaw.energy;$('#alchemy-energy-reserve').value=alchemyRaw.energy_reserve;if(legacy)$('#alchemy-batches').value=alchemyRaw.batches;
  $('#alchemy-mode').textContent=legacy?'旧版单配方 · 数量仍是制作批次，打开和保存不会悄悄改变语义。可明确转换成独立的产出目标副本。':'目标模式 · 按产出件数与明确材料选择规划；目标共同扣除同一库存与能量。';const actions=$('#alchemy-target-actions');if(actions?.children[0])actions.children[0].hidden=legacy;if(actions?.children[1])actions.children[1].hidden=!legacy;
  const recipe=alchemyRecipe(),family=alchemyFamily($('#alchemy-recipe').value);$('#alchemy-formula').textContent=alchemyRecipeDescription(legacy?recipe:family);const source=legacy?recipe?.source:family?.source;if(source?.url)$('#alchemy-source-link').href=source.url;renderAlchemyTargets();renderAlchemyChains();renderAlchemyMaterials();renderAlchemyOrigin();
}
function alchemyRawChoices(raw){return Object.fromEntries(Object.entries(raw||{}).map(([key,value])=>[key,Array.isArray(value)?[...value]:value==null?'':String(value)]));}
function alchemyRawState(raw){return Object.fromEntries(Object.entries(raw||{}).map(([key,value])=>[key,Array.isArray(value)?[...value]:value==null?(key==='rolled_choices'?['','','','']:''):String(value)]));}
function rawAlchemyParams(params){const raw={...alchemyClone(params),energy:String(params.energy),energy_reserve:String(params.energy_reserve)};raw.resources=params.resources.map(row=>({...alchemyClone(row),quantity:String(row.quantity),reserve:String(row.reserve),...(params.format===2?{state:alchemyRawState(row.state)}:{})}));if(params.format===2){raw.targets=params.targets.map(row=>({...row,quantity:String(row.quantity),choices:alchemyRawChoices(row.choices)}));raw.chains=Object.fromEntries(Object.entries(params.chains).map(([id,row])=>[id,{recipe:row.recipe,choices:alchemyRawChoices(row.choices)}]));}else raw.batches=String(params.batches);return raw;}
function validateAlchemyRaw(raw){
  if(!raw||typeof raw!=='object'||Array.isArray(raw)||JSON.stringify(raw).length>1048576)throw new Error('炼金原始草稿格式或大小不正确；原副本保留');
  const text=value=>typeof value==='string'&&value.length<=200,id=value=>typeof value==='string'&&/^(?:items|plants)\.[a-z0-9_.$-]{1,290}$/.test(value),key=value=>typeof value==='string'&&/^[A-Za-z0-9_.:-]{1,100}$/.test(value),recipe=value=>typeof value==='string'&&/^[a-z0-9-]{1,100}$/.test(value);
  if(raw.picker_recipe!==undefined&&!text(raw.picker_recipe)||raw.picker_quantity!==undefined&&!text(raw.picker_quantity))throw new Error('炼金新增目标的原始选择格式不正确');
  if(!text(raw.energy)||!text(raw.energy_reserve)||!['manual','known'].includes(raw.energy_origin)||raw.reference_version!==null&&(!Number.isInteger(raw.reference_version)||raw.reference_version<0||raw.reference_version>2147483647))throw new Error('炼金原始能量或来源格式不正确');if(raw.recipe_version!==undefined&&(typeof raw.recipe_version!=='string'||!/^\d[\d.]{0,39}$/.test(raw.recipe_version)))throw new Error('炼金原始版本不正确');
  const checkChoices=values=>{if(!values||typeof values!=='object'||Array.isArray(values)||Object.keys(values).some(name=>!Object.hasOwn(alchemyChoiceLabels,name)))throw new Error('原始配方选择字段不正确');for(const [name,value] of Object.entries(values)){if(['source_keys','seed_ids'].includes(name)){if(!Array.isArray(value)||value.length>64||value.some(v=>!text(v)||v!==''&&!(name==='source_keys'?key(v):id(v))))throw new Error('原始材料选择列表不正确');}else if(!text(value))throw new Error('原始配方选择需保留为文本');}};
  if(!Array.isArray(raw.resources)||raw.resources.length>(raw.format===2?256:64))throw new Error('炼金原始库存列表不正确');const seen=new Set();
  for(const row of raw.resources){if(!row||!id(row.id)||!text(row.quantity)||!text(row.reserve)||!['manual','known'].includes(row.origin))throw new Error('炼金原始材料字段不正确');const token=raw.format===2?row.key:row.id;if(raw.format===2&&!key(token)||seen.has(token))throw new Error('原始库存实例标识重复或不正确');seen.add(token);if(raw.format===2){if(!row.state||typeof row.state!=='object'||Array.isArray(row.state))throw new Error('物品原始状态格式不正确');for(const [name,value] of Object.entries(row.state)){if(!Object.hasOwn(alchemyStateLabels,name))throw new Error('物品原始状态字段不正确');if(name==='rolled_choices'){if(!Array.isArray(value)||value.length!==4||value.some(v=>!text(v)||v!==''&&!id(v)))throw new Error('触媒四个原始选项不正确');}else if(!text(value))throw new Error('物品原始状态需保留为文本');}}}
  if(raw.format===2){if(!Array.isArray(raw.targets)||raw.targets.length>64||!raw.chains||typeof raw.chains!=='object'||Array.isArray(raw.chains)||Object.keys(raw.chains).length>256)throw new Error('炼金原始目标或前置路径不正确');const seenTargets=new Set();for(const row of raw.targets){if(!key(row.key)||seenTargets.has(row.key)||!recipe(row.recipe)||!text(row.quantity))throw new Error('炼金原始目标字段不正确');seenTargets.add(row.key);checkChoices(row.choices);}for(const [output,row] of Object.entries(raw.chains)){if(!id(output)||!recipe(row.recipe))throw new Error('炼金原始前置配方不正确');checkChoices(row.choices);}}
  else if(raw.format!==undefined||!recipe(raw.recipe)||!text(raw.batches))throw new Error('旧炼金原始配方或批次不正确');return alchemyClone(raw);
}
function applyAlchemyRaw(raw){const copy=validateAlchemyRaw(raw);delete copy.picker_recipe;delete copy.picker_quantity;alchemyRaw=copy;alchemyRaw.recipe_version??='4.0.2';renderAlchemyEditor();if(raw.picker_recipe!==undefined){alchemyOptions($('#alchemy-recipe'),(alchemyRaw.format===2?alchemyFamilies:alchemyRecipes).map(row=>[row.id,row.name]),raw.picker_recipe);$('#alchemy-batches').value=raw.picker_quantity??'1';}}
function convertAlchemyLegacy(){captureAlchemyFields();if(alchemyRaw.format===2)return;const recipe=alchemyRecipes.find(row=>row.id===alchemyRaw.recipe);if(!recipe||alchemyRaw.recipe_version!=='4.0.2')throw new Error('旧配方或版本未核对，不能推测转换数量；原方案保留');const quantity=alchemyNumber(alchemyRaw.batches,'旧批次')*recipe.quantity;if(!Number.isSafeInteger(quantity)||quantity>2147483647)throw new Error('换算产出超出游戏上限，请先调整批次');alchemyRaw={format:2,recipe_version:'4.0.2',targets:[{key:'goal-'+(++alchemySerial),recipe:recipe.id,quantity:String(quantity),choices:{}}],resources:alchemyRaw.resources.map(row=>({...row,key:'manual-'+(++alchemySerial),state:{}})),energy:alchemyRaw.energy,energy_reserve:alchemyRaw.energy_reserve,energy_origin:alchemyRaw.energy_origin,reference_version:alchemyRaw.reference_version,chains:{}};alchemySavedPlan=null;alchemyResult=null;alchemyUndo=null;alchemyChanged();renderAlchemyEditor();renderAlchemyResult();toast('已创建独立的产出目标副本，原命名方案保留。');}
function renderAlchemyOrigin(){
  if(!$('#alchemy-status'))return;const current=typeof state==='undefined'?null:state,changed=alchemySource.mode==='save'&&current&&(alchemySource.snapshot_at!==current.modified||alchemySource.slot!==(current.active_slot??null)||current.error||current.settings?.mode&&current.settings.mode!=='save');
  $('#alchemy-status').textContent=(alchemySavedPlan?'固定方案「'+alchemySavedPlan.name+'」':alchemySource.mode==='save'?'明确带入的固定存档参考':'明确手填假设')+(alchemySource.snapshot_at?' · '+fmtTime(alchemySource.snapshot_at):'')+'。材料不会自动跟随当前角色。'+(changed?'当前快照已变化，请核对后明确重新带入；旧条件保留。':'')+(alchemyDirty?'原始输入已变化，以下旧结果尚未重算。':alchemyUnsaved?'当前结果尚未命名保存。':'')+(alchemyRuleChanged?'保存或读取时的规则不同，请核对当前4.0.2；原条件不会自动改版。':'')+(alchemySavedPlan?.note?' 用途 / 假设：'+alchemySavedPlan.note:'');$('#alchemy-energy-origin').textContent=alchemyRaw.energy_origin==='known'?'固定存档的Dungeon能量；没有自动计入未确认可用的工具包。':'明确手填本次可支配总量，可包含已经确认可用的工具包；未确认时请勿计入。';
  $('#alchemy-save').disabled=alchemyPending||alchemyDirty||!alchemyResult;$('#alchemy-copy').disabled=alchemyPending||alchemyDirty||!alchemyResult;$('#alchemy-undo').disabled=!alchemyUndo;$('#alchemy-reload-saved').hidden=!alchemySavedPlan;for(const row of alchemyRaw.resources){const node=$('[data-alchemy-origin="'+(row.key||row.id)+'"]');if(node)node.textContent=row.origin==='known'?'固定存档参考的已知实例':'明确手填身份、数量或状态，尚未经游戏确认';}renderAlchemyPlanMetadata();
}
function alchemyStateText(values){return Object.entries(values||{}).map(([key,value])=>{const label=alchemyStateLabels[key]||key;if(value==null||value===''||Array.isArray(value)&&value.every(v=>!v))return label+'未知';if(Array.isArray(value))return label+'：'+value.map(alchemyName).join(' / ');const known=alchemyEnums[key]?.find(row=>row[0]===String(value));return label+'：'+(known?.[1]||(key==='potion_id'?alchemyName(value):String(value)));}).join('；');}
function alchemyChoiceText(values){return Object.entries(values||{}).map(([key,value])=>(alchemyChoiceLabels[key]||key)+'：'+(Array.isArray(value)?value.map(v=>key==='source_keys'?v:alchemyName(v)).join(' / '):key==='selection'?'第'+(Number(value)+1)+'项':key.endsWith('_id')?alchemyName(value):value)).join('；')||'无额外材料选择';}
function alchemyYieldText(row){if(!row)return '未确定';return (row.id?alchemyName(row.id):'随机 / 未确定身份')+' ×'+(row.quantity==null?'未知':row.quantity)+' 件'+(row.yield_bounds?'（条件产量 '+row.yield_bounds.minimum+'–'+row.yield_bounds.maximum+'；'+row.yield_bounds.condition+'）':'')+(alchemyStateText(row.state)?'；'+alchemyStateText(row.state):'');}
function alchemyTable(parent,labels,rows){const wrap=alchemyNode('div','','table-scroll'),table=alchemyNode('table'),head=alchemyNode('thead'),header=alchemyNode('tr');for(const label of labels)header.append(alchemyNode('th',label));head.append(header);table.append(head);const body=alchemyNode('tbody');for(const values of rows){const row=alchemyNode('tr');for(const value of values)row.append(alchemyNode('td',alchemyText(value)));body.append(row);}table.append(body);wrap.append(table);parent.append(wrap);}
function alchemyStepText(step){return (alchemyFamily(step.recipe)?.name||step.recipe)+(step.level_after!==undefined?' +'+step.level_before+' → +'+step.level_after:' · '+step.batches+'批')+'；'+(step.inputs||[]).map(row=>alchemyName(row.id)+' ×'+row.quantity+' ['+row.key+'；'+(row.origin==='known'?'已知快照':row.origin==='planned'?'前置产出':'手填假设')+']'+(alchemyStateText(row.state)?' '+alchemyStateText(row.state):'')).join(' + ')+' → '+alchemyYieldText(step.output)+'；能量 '+step.energy.before+' − '+step.energy.spent+' = '+step.energy.after+' 点';}
function alchemyProbabilityText(probability){return '三个种子含 '+probability.distinct_seeds+' 种身份，先抽默认药池的概率 '+(100*probability.default_pool_chance)+'%；其余分支按三个种子槽抽取。治疗重抽前的初始概率：'+Object.entries(probability.initial_probabilities_before_healing_reroll||{}).filter(([,value])=>value.numerator).map(([id,value])=>alchemyName(id)+' '+value.numerator+'/'+value.denominator).join('；')+'。'+probability.healing_reroll;}
function renderAlchemySteps(root,steps){
  for(const [index,step] of (steps||[]).entries()){const card=alchemyNode('article');card.append(alchemyNode('h3','步骤 '+(index+1)+' · '+(step.key||'')+' · 目标 '+step.target),alchemyNode('p',alchemyStepText(step)));if(step.cooking_counts)card.append(alchemyNode('p','实际炖肉批次组合：'+Object.entries(step.cooking_counts).map(([size,count])=>size+'件一批 ×'+count).join('；'),'muted'));if(step.probability){card.append(alchemyNode('p',alchemyProbabilityText(step.probability),'muted'));alchemyTable(card,['药剂身份','治疗重抽前的初始概率'],Object.entries(step.probability.initial_probabilities_before_healing_reroll).map(([id,value])=>[alchemyName(id),value.numerator+'/'+value.denominator]));}if(step.source?.url&&/^https:\/\/github\.com\//.test(step.source.url)){const link=alchemyNode('a','官方4.0.2配方源码（GPL-3.0-or-later）');link.href=step.source.url;link.target='_blank';link.rel='noopener noreferrer';card.append(link);}root.append(card);}
}
function alchemyShortageText(row){return (row.target?'目标 '+row.target+' · ':'')+(row.id==='energy'?'能量':alchemyChoiceLabels[row.id]||alchemyName(row.id))+'：需要 '+row.required+'，可用 '+row.available+'，缺少 '+row.missing+'；'+row.reason;}
function renderAlchemyShortages(root,rows,editable=true,depth=0){
  if(depth>16)return;for(const row of rows||[]){const card=alchemyNode('div','','rule-warning');card.append(alchemyNode('p',alchemyShortageText(row)));if(row.options?.length){const label=alchemyNode('label','可选择的生产路径（每项含具体材料选择）'),select=alchemyNode('select');alchemyOptions(select,row.options.map((option,index)=>[String(index),(alchemyFamily(option.recipe)?.name||option.recipe)+' · '+alchemyChoiceText(option.choices)]),'');label.append(select);card.append(label);const button=alchemyButton('明确采用此路径并重算',()=>{if(alchemyDirty)throw new Error('此生产路径来自旧条件，请先重算当前条件');captureAlchemyFields();if(alchemyRaw.format!==2)throw new Error('生产路径需在目标模式中选择');const option=row.options[Number(select.value)];if(select.value===''||!option)throw new Error('请明确选择生产路径');alchemyRaw.chains[row.id]={recipe:option.recipe,choices:alchemyRawChoices(option.choices)};alchemyChanged();renderAlchemyEditor();return calculateAlchemy();});button.disabled=!editable;alchemyProducerButtons.push(button);card.append(button);}if(row.dependency)renderAlchemyShortages(card,[row.dependency],editable,depth+1);root.append(card);}
}
function alchemyCopyText(result=alchemyResult){
  if(!result)return '';const lines=['炼金规划 · 官方 '+result.version+' · '+result.commit,'固定来源：'+JSON.stringify(cleanStoredOrigin(alchemySource))];
  if(result.format===2){lines.push('按产出件数；目标顺序共享库存、保留与能量。',...result.targets.map(row=>'目标 '+row.key+'：'+(alchemyFamily(row.recipe)?.name||row.recipe)+'；请求 '+row.requested_quantity+' 件；预算内 '+row.planned_quantity+' 件；缺 '+row.shortfall+' 件；'+alchemyChoiceText(row.choices)),...Object.entries(result.params.chains).map(([id,row])=>'明确前置路径：'+alchemyName(id)+' ← '+(alchemyFamily(row.recipe)?.name||row.recipe)+'；'+alchemyChoiceText(row.choices)),...result.steps.flatMap(step=>[alchemyStepText(step),step.probability?alchemyProbabilityText(step.probability):'',step.source?.url||'']),...result.outputs.map(row=>'认领成品 '+row.target+'：'+alchemyYieldText(row)+'；使用前序富余 '+row.from_surplus+' 件'),...result.surplus.map(row=>'可复用富余：'+row.key+' · '+alchemyYieldText(row)),...result.shortages.map(alchemyShortageText),...result.pending_conditions.map(row=>'待确认：'+row.condition),...result.outcome_boundaries.map(row=>'结果边界：'+row.message));}
  else lines.push('旧方案：'+result.recipe.name+'；每批产出 '+result.recipe.quantity+' 件；请求 '+result.requested_batches+' 批；预算内 '+result.batches+' 批；最大 '+result.max_batches+' 批','产出：'+alchemyYieldText(result.output),'预算限制：'+result.limiting.map(row=>row.label+'（'+row.reason+'）').join('；'),...result.limits.map(row=>row.label+'：'+row.formula+' = '+row.max_batches+' 批'),result.recipe.source.url);
  lines.push(...result.materials.map(row=>(row.key?row.key+' · ':'')+(row.name||alchemyName(row.id))+'：原量 '+row.quantity+' 件；保留 '+row.reserve+' 件；消耗 '+row.spent+' 件；剩余 '+row.remaining+' 件；可再用 '+row.spendable_remaining+' 件；来源 '+row.origin+(alchemyStateText(row.state)?'；'+alchemyStateText(row.state):'')),'能量：原量 '+result.energy.quantity+' 点；保留 '+result.energy.reserve+' 点；消耗 '+result.energy.spent+' 点；剩余 '+result.energy.remaining+' 点；可再用 '+result.energy.spendable_remaining+' 点；来源 '+result.energy.origin,...result.warnings,alchemySavedPlan?.note?'用途 / 假设：'+alchemySavedPlan.note:'');return lines.filter(Boolean).join('\n');
}
function renderAlchemyResult(){
  const root=$('#alchemy-result');if(!root)return;alchemyProducerButtons=[];root.replaceChildren();if(!alchemyResult){root.append(alchemyNode('p','填写目标、原始库存实例、能量和最低保留，再明确计算。','muted'));$('#alchemy-copy-text').textContent='';return;}const result=alchemyResult,stale=alchemyNode('p','原始条件已经修改；下方仍是上次固定条件的结果，请重新计算。','rule-warning');stale.id='alchemy-stale';stale.hidden=!alchemyDirty;root.append(stale,alchemyNode('h2',result.format===2?'共享账本 · '+(result.complete?'确定完成':result.within_budget?'预算内仍有待确认或随机结果':'部分目标不足'):'旧批次方案 · '+(result.within_budget?'预算内':'超出预算')));
  if(result.format===2){alchemyTable(root,['目标与配方','要求产出（件）','预算内制作（件）','不足（件）','明确选择'],result.targets.map(row=>[row.key+' · '+(alchemyFamily(row.recipe)?.name||row.recipe),row.requested_quantity,row.planned_quantity,row.shortfall,alchemyChoiceText(row.choices)]));root.append(alchemyNode('h3','可执行的模拟制作顺序'));renderAlchemySteps(root,result.steps);if(!result.steps.length)root.append(alchemyNode('p','当前没有已满足条件的制作步骤。','muted'));if(result.requested_steps.some(row=>row.status==='pending')){const details=alchemyNode('details');details.append(alchemyNode('summary','请求的完整计划中尚不能落实的步骤'));for(const row of result.requested_steps.filter(row=>row.status==='pending'))details.append(alchemyNode('p',(alchemyFamily(row.recipe)?.name||row.recipe)+' · 要求 '+row.requested_quantity+' 件；'+row.reason));root.append(details);}root.append(alchemyNode('h3','已认领成品'));for(const row of result.outputs)root.append(alchemyNode('p','目标 '+row.target+'：'+alchemyYieldText(row)+'；已用前序富余 '+row.from_surplus+' 件'));root.append(alchemyNode('h3','仍可复用的富余'));for(const row of result.surplus)root.append(alchemyNode('p',row.key+' · '+alchemyYieldText(row)));if(!result.surplus.length)root.append(alchemyNode('p','没有未认领富余。','muted'));renderAlchemyShortages(root,result.shortages,!alchemyDirty);for(const row of result.pending_conditions)root.append(alchemyNode('p','待确认 · '+row.target+'：'+row.condition,'rule-warning'));for(const row of result.outcome_boundaries)root.append(alchemyNode('p','结果边界 · '+row.target+'：'+row.message,'rule-warning'));}
  else{root.append(alchemyNode('p',result.recipe.name+'：请求 '+result.requested_batches+' 批；预算内 '+result.batches+' 批；当前最多 '+result.max_batches+' 批。产出 '+result.output.quantity+' 件。'));alchemyTable(root,['限制','最大批次','公式'],result.limits.map(row=>[row.label,row.max_batches,row.formula]));}
  root.append(alchemyNode('h3','原始材料账本（件）'));alchemyTable(root,['实例 / 身份','原量','最低保留','实际消耗','剩余','可再用','来源与条件'],result.materials.map(row=>[(row.key?row.key+' · ':'')+(row.name||alchemyName(row.id)),row.quantity,row.reserve,row.spent,row.remaining,row.spendable_remaining,(row.origin==='known'?'固定已知快照':'明确手填假设')+(alchemyStateText(row.state)?'；'+alchemyStateText(row.state):'')]));alchemyTable(root,['能量（点）','原量','最低保留','实际消耗','剩余','可再用'],[['同一能量预算',result.energy.quantity,result.energy.reserve,result.energy.spent,result.energy.remaining,result.energy.spendable_remaining]]);root.append(alchemyNode('p',result.warnings.join(' '),'muted'));$('#alchemy-copy-text').textContent=alchemyCopyText();
}
async function calculateAlchemy(){
  if(!alchemyInitialized||!$('#alchemy-form').reportValidity())return;const seq=++alchemyRequest,generation=alchemyGeneration;alchemyPending=true;alchemyPendingRequest=seq;$('#alchemy-calculate').disabled=true;renderAlchemyOrigin();try{const params=alchemyParams(),response=await post('/api/workspace',{action:'alchemy-calculate',params});if(seq!==alchemyRequest||generation!==alchemyGeneration)return;alchemyResult=response.result;alchemyDirty=false;alchemyUnsaved=true;renderAlchemyResult();inlineError($('#alchemy-error'),'');}catch(error){if(seq===alchemyRequest&&generation===alchemyGeneration)inlineError($('#alchemy-error'),error.message);}finally{if(alchemyPendingRequest===seq){alchemyPending=false;$('#alchemy-calculate').disabled=false;renderAlchemyOrigin();}}
}
async function useAlchemyResources(){
  captureAlchemyFields();const generation=alchemyGeneration;$('#alchemy-use-resources').disabled=true;try{const reference=await post('/api/workspace',{action:'alchemy-resources'});if(generation!==alchemyGeneration)throw new Error('带入期间原始表单已修改，当前编辑保留；请核对后再带入');if(!reference.compatible)throw new Error(reference.message);const before={raw:captureAlchemyRaw(),source:alchemyClone(alchemySource),saved:alchemyClone(alchemySavedPlan),result:alchemyClone(alchemyResult),dirty:alchemyDirty,unsaved:alchemyUnsaved,rule_changed:alchemyRuleChanged,discovery:alchemyClone(alchemyDiscovery),discovery_current:alchemyDiscoveryGeneration===alchemyGeneration};
    let resources;if(alchemyRaw.format===2){if(!Array.isArray(reference.instances))throw new Error('参考没有原始库存实例，不能从同身份总量推测物品状态');const prior=new Map(alchemyRaw.resources.map(row=>[row.key,row]));resources=reference.instances.map(row=>{const old=prior.get(row.key),unchanged=old&&old.id===row.id&&JSON.stringify(alchemyRawState(row.state))===JSON.stringify(old.state);return {...alchemyClone(row),quantity:String(row.quantity),reserve:unchanged?old.reserve:old?'':'0',origin:'known',state:alchemyRawState(row.state)};});}else{const recipe=alchemyRecipe();if(!recipe)throw new Error('请先选择已核对的旧配方');resources=recipe.inputs.map(ingredient=>{const old=alchemyRaw.resources.find(row=>row.id===ingredient.id),known=reference.resources.find(row=>row.id===ingredient.id);return {id:ingredient.id,quantity:String(known?.quantity??0),reserve:old?.reserve??'0',origin:'known'};});}
    const next={...alchemyClone(alchemyRaw),resources,energy:reference.energy==null?'':String(reference.energy),energy_origin:reference.energy==null?'manual':'known',reference_version:reference.reference_version};validateAlchemyRaw(next);alchemyRaw=next;alchemySource=cleanStoredOrigin(reference.source);alchemyUndo=before;alchemyChanged();renderAlchemyEditor();renderAlchemyResult();renderAlchemyDiscovery();inlineError($('#alchemy-error'),'');toast('已替换为固定快照的已知库存实例，尚未重算；状态变化的原实例保留量需重新确认，其他保留量未截断。');
  }catch(error){inlineError($('#alchemy-error'),error.message);}finally{$('#alchemy-use-resources').disabled=false;}
}
function undoAlchemyResources(){if(!alchemyUndo)return;const before=alchemyUndo;applyAlchemyRaw(before.raw);alchemySource=alchemyClone(before.source);alchemySavedPlan=alchemyClone(before.saved);alchemyResult=alchemyClone(before.result);alchemyDirty=before.dirty;alchemyUnsaved=before.unsaved;alchemyRuleChanged=before.rule_changed;alchemyDiscovery=alchemyClone(before.discovery);alchemyUndo=null;alchemyGeneration++;alchemyRequest++;alchemyDiscoveryRequest++;alchemyDiscoveryGeneration=before.discovery_current?alchemyGeneration:-1;renderAlchemyResult();renderAlchemyDiscovery();renderAlchemyOrigin();toast('已撤回最近一次带入，完整恢复当时的原始输入、选择、路径、来源和结果。');}
async function discoverAlchemy(){
  if(alchemyRaw.format!==2){inlineError($('#alchemy-error'),'旧方案仍按批次计算；请明确转换副本后再发现多目标候选');return;}const seq=++alchemyDiscoveryRequest,generation=alchemyGeneration;alchemyDiscoveryPendingRequest=seq;$('#alchemy-discover').disabled=true;try{const params=alchemyParams(false);delete params.targets;const response=await post('/api/workspace',{action:'alchemy-discover',params});if(seq!==alchemyDiscoveryRequest||generation!==alchemyGeneration)return;alchemyDiscovery=response.result||response;alchemyDiscoveryGeneration=generation;renderAlchemyDiscovery();inlineError($('#alchemy-error'),'');}catch(error){if(seq===alchemyDiscoveryRequest)inlineError($('#alchemy-error'),error.message);}finally{if(alchemyDiscoveryPendingRequest===seq)$('#alchemy-discover').disabled=false;}
}
function renderAlchemyDiscovery(){
  const root=$('#alchemy-discovery-list'),status=$('#alchemy-discovery-status');if(!root)return;root.replaceChildren();if(!alchemyDiscovery){status.textContent='明确预览后显示候选。这里不穷尽所有材料组合；可在目标中手动选择其他合格材料。';return;}const stale=alchemyDiscoveryGeneration!==alchemyGeneration,labels={immediate:'当前预算可制作', 'with-prerequisites':'需要先制作前置材料','needs-condition':'状态 / 选择待确认','needs-energy':'能量不足','needs-material':'材料不足','random-outcome':'预算内有随机结果'};status.textContent=(stale?'条件已变化，以下是旧库存的候选，重新预览后才能加入。':'')+(alchemyDiscovery.message||'每项独立预览；加入多个目标后必须重算共享账本。');
  for(const row of alchemyDiscovery.recipes||[]){const card=alchemyNode('details');card.append(alchemyNode('summary',row.name+' · '+(labels[row.availability]||row.availability)),alchemyNode('p','请求产出 '+row.target.quantity+' 件；'+alchemyChoiceText(row.target.choices)));for(const step of row.steps||[])card.append(alchemyNode('p',alchemyStepText(step),'muted'));for(const shortage of row.shortages||[])card.append(alchemyNode('p',alchemyShortageText(shortage),'rule-warning'));for(const pending of row.pending_conditions||[])card.append(alchemyNode('p','待确认：'+pending.condition,'rule-warning'));for(const boundary of row.outcome_boundaries||[])card.append(alchemyNode('p','结果边界：'+boundary.message,'rule-warning'));const button=alchemyButton('以这些明确选择加入目标',()=>{if(alchemyDiscoveryGeneration!==alchemyGeneration)throw new Error('候选条件已过时，请重新预览');addAlchemyTarget(row.target.recipe,String(row.target.quantity),row.target.choices);toast('已加入目标；请重算共同库存与能量。');});button.disabled=stale;card.append(button);root.append(card);}
}
async function openAlchemyPlan(plan,result,rulesChanged){
  const request=++alchemyOpenRequest,generation=alchemyGeneration,nav=navigationSerial;
  await loadAlchemy();
  if(request!==alchemyOpenRequest||generation!==alchemyGeneration||nav!==navigationSerial||webEditingFrozen){
    if(nav===navigationSerial&&!webEditingFrozen&&request===alchemyOpenRequest)inlineError($('#alchemy-error'),'读取期间炼金表单已有新编辑；当前原始输入仍保留，请核对后重新打开方案。');
    return false;
  }
  if(!alchemyInitialized){inlineError($('#alchemy-error'),'炼金资料暂未就绪；当前输入仍保留，请重试读取后再打开方案。');return false;}
  const raw=rawAlchemyParams(plan.params);validateAlchemyRaw(raw);applyAlchemyRaw(raw);
  alchemySavedPlan=alchemyClone(plan);alchemySource=cleanStoredOrigin(plan.origin);alchemyResult=alchemyClone(result);
  alchemyDirty=false;alchemyUnsaved=false;alchemyUndo=null;alchemyRuleChanged=!!rulesChanged||plan.params.recipe_version!=='4.0.2';alchemyDiscovery=null;
  alchemyGeneration++;alchemyRequest++;alchemyDiscoveryRequest++;alchemyPending=false;alchemyPendingRequest=0;alchemyDiscoveryPendingRequest=0;
  $('#alchemy-calculate').disabled=false;$('#alchemy-discover').disabled=false;
  renderAlchemyResult();renderAlchemyDiscovery();renderAlchemyOrigin();$('#alchemy-targets').focus();return true;
}
function alchemyPlanSaved(plan,payload){const matches=alchemyResult&&JSON.stringify(alchemyResult.params)===JSON.stringify(payload.params)&&JSON.stringify(cleanStoredOrigin(alchemySource))===JSON.stringify(cleanStoredOrigin(payload.source));if(matches){alchemySavedPlan=alchemyClone(plan);alchemyUnsaved=alchemyDirty;renderAlchemyOrigin();}}
function saveAlchemyPlan(){if(!alchemyResult||alchemyDirty||alchemyPending){inlineError($('#alchemy-error'),'请先重新计算当前原始输入，再命名保存');return;}const name=alchemyResult.format===2?(alchemyFamily(alchemyResult.targets[0]?.recipe)?.name||'多目标炼金')+'规划':alchemyResult.recipe.name+'规划';openPlanSave({kind:'alchemy',entry:null,params:alchemyClone(alchemyResult.params),source:alchemyClone(alchemySource),note:alchemySavedPlan?.note||''},alchemySavedPlan?alchemyClone(alchemySavedPlan):null,name);}
function alchemyDraftLabel(){return alchemyDirty||alchemyUnsaved?'炼金规划':null;}
function captureAlchemyDraft(){return alchemyDraftLabel()?{raw:captureAlchemyRaw(),source:alchemyClone(alchemySource),saved_id:alchemySavedPlan?.id||null,saved_revision:alchemySavedPlan?.record_revision||null,saved_name:alchemySavedPlan?.name||null,saved_origin:alchemySavedPlan?.origin||null,note:alchemySavedPlan?.note||''}:null;}
async function restoreAlchemyDraft(draft,checkRecovery=()=>{}){
  if(!draft||typeof draft.note!=='string'||draft.note.length>1200||draft.saved_revision!=null&&(typeof draft.saved_revision!=='string'||draft.saved_revision!==''&&!/^[a-f0-9]{64}$/.test(draft.saved_revision))||draft.saved_name!=null&&(typeof draft.saved_name!=='string'||draft.saved_name.length>80)||draft.saved_id!=null&&(typeof draft.saved_id!=='string'||draft.saved_id.length>200))throw new Error('炼金备注、名称或原始关联版本不正确；当前编辑保留');const raw=validateAlchemyRaw(draft.raw),source=cleanStoredOrigin(draft.source);await loadAlchemy();checkRecovery();const generation=alchemyGeneration;let saved=null;if(draft.saved_id){try{const latest=(await getJSON('/api/workspace/plan?'+new URLSearchParams({id:draft.saved_id}))).plan;if(latest.kind==='alchemy')saved={...latest,record_revision:draft.saved_revision||'',name:draft.saved_name??latest.name,origin:cleanStoredOrigin(draft.saved_origin||latest.origin),note:draft.note};}catch(error){toast('关联方案暂不可读；按独立原始草稿恢复，原副本保留。',true);}}
  checkRecovery();if(generation!==alchemyGeneration)throw new Error('恢复期间当前表单已修改，本次恢复未覆盖当前编辑；原副本保留');if(!saved&&draft.saved_id)saved={id:draft.saved_id,kind:'alchemy',name:draft.saved_name||'原关联炼金方案',record_revision:draft.saved_revision||'',origin:cleanStoredOrigin(draft.saved_origin||source),note:draft.note};applyAlchemyRaw(raw);alchemySavedPlan=saved;alchemySource=source;alchemyResult=null;alchemyUndo=null;alchemyDiscovery=null;alchemyDirty=true;alchemyUnsaved=true;alchemyRuleChanged=!!raw.recipe_version&&raw.recipe_version!=='4.0.2';alchemyGeneration++;alchemyRequest++;alchemyDiscoveryRequest++;renderAlchemyResult();renderAlchemyDiscovery();renderAlchemyOrigin();
}
function rememberAlchemyPlanMetadata(draft,name,note){if(draft?.payload.kind!=='alchemy')return;const key=planDraftKey(draft.payload,draft.existing),original=planMetaOriginals.get(key);if(original&&original.name===name&&original.note===note){alchemyPlanMetadata.delete(key);return;}alchemyPlanMetadata.set(key,{key,payload:alchemyClone(draft.payload),existing:draft.existing?alchemyClone(draft.existing):null,name,note});renderAlchemyPlanMetadata();}
function clearAlchemyPlanMetadata(key){alchemyPlanMetadata.delete(key);renderAlchemyPlanMetadata();}
function captureAlchemyPlanMetadata(){return Array.from(alchemyPlanMetadata.values()).map(alchemyClone);}
function restoreAlchemyPlanMetadata(rows){if(!Array.isArray(rows)||rows.length>200)throw new Error('炼金命名草稿格式不正确');for(const row of rows){if(!row||typeof row.key!=='string'||row.key.length>400||row.payload?.kind!=='alchemy'||typeof row.name!=='string'||row.name.length>80||typeof row.note!=='string'||row.note.length>1200)throw new Error('炼金命名草稿格式不正确');}for(const row of rows)alchemyPlanMetadata.set(row.key,alchemyClone(row));renderAlchemyPlanMetadata();}
function renderAlchemyPlanMetadata(){const root=$('#alchemy-pending-meta');if(!root)return;root.replaceChildren();for(const row of alchemyPlanMetadata.values())root.append(alchemyButton('继续名称 / 备注草稿：'+(row.name||'未命名方案'),()=>{openPlanSave(alchemyClone(row.payload),row.existing?alchemyClone(row.existing):null,row.name);$('#plan-name').value=row.name;$('#plan-note').value=row.note;}));}
if($('#alchemy-form')){
  $('#alchemy-form').addEventListener('submit',event=>{event.preventDefault();calculateAlchemy();});
  $('#alchemy-recipe').addEventListener('change',()=>{if(alchemyRaw.format!==2){const old=alchemyRaw.resources;alchemyRaw.recipe=$('#alchemy-recipe').value;alchemyRaw.resources=(alchemyRecipe()?.inputs||[]).map(row=>old.find(item=>item.id===row.id)||{id:row.id,quantity:'0',reserve:'0',origin:'manual'});alchemyChanged();}renderAlchemyEditor();});
  for(const id of ['alchemy-energy','alchemy-energy-reserve','alchemy-batches'])$('#'+id).addEventListener('input',()=>{if(id==='alchemy-energy'&&alchemyRaw.energy!==$('#'+id).value)alchemyRaw.energy_origin='manual';captureAlchemyFields();alchemyChanged();});
  $('#alchemy-use-resources').addEventListener('click',useAlchemyResources);$('#alchemy-undo').addEventListener('click',undoAlchemyResources);$('#alchemy-save').addEventListener('click',saveAlchemyPlan);$('#alchemy-reload-saved').addEventListener('click',()=>{if(alchemySavedPlan)confirmReloadSavedPlan(alchemySavedPlan.id);});
  $('#alchemy-copy').addEventListener('click',async()=>{try{if(alchemyDirty||alchemyPending||!alchemyResult)throw new Error('请先计算当前条件');await navigator.clipboard.writeText(alchemyCopyText());$('#alchemy-copy-status').textContent='已复制完整目标、明确选择、实例账本、单位、来源与保留预算';}catch(error){$('#alchemy-copy-status').textContent='可在下方选择完整方案文本复制。'+error.message;}});
}
